MN-Script-Team/DHS-MAXIS-Scripts

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

This will be useful for determining if we're scriptwriters or not, as
scriptwriters typically use C:\DHS-MAXIS-Scripts\Script Files\ as the
location of their scripts.

Now checks "default directory"

---

Name your file…

Well, I am going try resubmitting this.  I did try to remove some do loops per your request, but I couldn't get it to work if I did.  Am sorry also as you will see ???????? for the directory or the functions files.  Not sure how this all works now with the new REDIRECT files.  Where do I go from here.  -)

NOTE - Mileage.vbs

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/MEMOS/MEMOS - MAIN MENU.vbs
Script Files/NAV/OTHER NAV/NAV - OTHER NAV MAIN MENU.vbs
Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs
Script Files/NOTES/NOTES - MAIN MENU - H-Z.vbs

Don't know how or why this was included here. Looks like a glitch in my
copy/pasting. Oh well.

Removed old "variables to declare", which are totally unneccessary

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/MEMOS/MEMOS - MAIN MENU.vbs
Script Files/NAV/OTHER NAV/NAV - OTHER NAV MAIN MENU.vbs
Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs
Script Files/NOTES/NOTES - MAIN MENU - H-Z.vbs

These were bug fixes, NBG, Resolved #321.

Moving Beta changes down to master

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/MEMOS/MEMOS - MAIN MENU.vbs
Script Files/NAV/OTHER NAV/NAV - OTHER NAV MAIN MENU.vbs
Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs
Script Files/NOTES/NOTES - MAIN MENU - H-Z.vbs

Also removes an Anoka-specific funclib redirect, used to test a funclib bug.

Merging Beta bug fixes to master

---

Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs
Script Files/NOTES/NOTES - MAIN MENU - H-Z.vbs

This reverts commit 5653ebf8abb337af65dfd63bd12d708661c8b547.

Revert "Setting NOTES - MAIN MENU files to test a funclib fix"

---

Script Files/NOTES/NOTES - OVERPAYMENT.vbs

Removed Anoka specific text. This has been run by a claims worker at
state, name is escaping us. He liked and advised on this current format.

Adding overpayment script

---

Script Files/ACTIONS/ACTIONS - SEND SVES.vbs

This required a minor dialog tweak and some additional coding. Nothing
major. I also changed `_radio` to `_radiobutton` where appropriate.
Resolve #184.

Send SVES now includes case note option

---

Script Files/BULK/BULK - REPT-EOMC LIST.vbs

@Farleight was right, the -1 didn't need to go in here. It was a
duplicate based on my copy/pasting of other functions. Sorry all!
While I was up-in-there, I also added the routine functions and some
basic variables, so that it doesn't require being run from the BULK -
MAIN MENU. Although, that's really how it should be used.

Resolved #304

---

Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/DAIL/DAIL - NEW HIRE.vbs

This resolves #241. @ramonalisa1, I think you'll like it. Simple and clean.

Added CEI/OHI checkbox to New hire and new job reported 

---

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

Added logic to check if HC renewals are MAGI ALL, MIXED, or NONE, and
edits the reinstate wording in the case note accordingly.

Revw update

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

Outdated code was causing data to overwrite itself. Updated code a bit.

Burial asset error/bug

---

Script Files/NOTES/NOTES - CAF.vbs

Fixed CAF issue

---

Script Files/AGENCY CUSTOMIZED/SOURCE/AGENCY CUSTOMIZED.vbs

Added support for folder to the Agency Custom Script

Added support for folders

---

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs

I failed to reinsert logic that automatically determine County of Financial Responsibility change date...

Fix to ACTIONS - TRANSFER CASE

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

Was previously causing an error when attempting to read the GA grant,  now fixed.

Bug fix for reading GA grant

---

Script Files/AGENCY CUSTOMIZED/SOURCE/AGENCY CUSTOMIZED.vbs

Added code to make the arrays more functional. At this time it appears this code is solid. The only issue we have been experiencing is while using GitRaw. I would like to see if this can be resolved by merging this over the current version.

County custom script revision

---

Script Files/AGENCY CUSTOMIZED/SOURCE/AGENCY CUSTOMIZED.vbs

Removed part of the dialog reset I believe was causing some issues.

Removed part of the dialog reset function.

---

Script Files/AGENCY CUSTOMIZED/SOURCE/AGENCY CUSTOMIZED.vbs

Reverted this month's changes back to the state of the file at the
beginning of February. The current version had a reported bug involving
dialog IDs. This commit should resolve #412.

Reverted this month's changes

---

Script Files/AGENCY CUSTOMIZED/SOURCE/AGENCY CUSTOMIZED.vbs
Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

bringing @CDPotter's MAGI fix to beta

---

Script Files/AGENCY CUSTOMIZED/SOURCE/AGENCY CUSTOMIZED.vbs

This is now a faster version that uses less memory on the users PC. The code has been restructured for readability. Old unnecessary code has been removed. This script is now "OPTION EXPLICIT" compliant and all variables are properly declared. Arrays have been removed and a lot of code has been condensed to make the script faster, more efficient, and more reliable.

Full restructure of code

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

enhancements adds full client address and option to include last 3 months benefits.  Resolves #367.

Update ACTIONS - PA VERIF REQUEST.vbs

---

Script Files/NOTES/NOTES - GRH - HRF.vbs

Added lines to make the checkbox for case noting elig information include a formatted version of client obligation. Supports client obligations up to $99,999.99.

Grh hrf obligation

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

Added three checkboxes: 1.  Primary beneficiary is...
2.  Contingent beneficiary is...
3.  Policy's CSV is...

Update NOTES - BURIAL ASSETS.vbs

---

Script Files/DAIL/DAIL - NEW HIRE.vbs

Updated DAIL - NEW HIRE

---

Script Files/NOTES/NOTES - DRUG FELON.vbs

This maxis case note would be utilizied for SNAP clients who have been convicted of a drug felony in the last 10 years and have to comply with UA's. This case note would track their UA results/test days and update case if changes need to be made to their benefits due to results of the UA's.

NOTES - DRUG FELON.vbs

---

Script Files/NOTES/NOTES - CHANGE REPORT FORM RECEIVED.vbs

Updated script again. Case noting change report form info.

NOTES - CHANGE REPORT FORM RECEIVED.vbs

---

Script Files/NOTES/NOTES - GAS CARDS ISSUED.vbs

I have made the 'select one' category mandatory, case noting gas cards issued.

NOTES - GAS CARDS ISSUED.vbs

---

Script Files/NOTES/NOTES - HCAPP.vbs

added select button and denied in hcapp status field

Update NOTES - HCAPP.vbs

---

Script Files/NOTES/NOTES - Medical Opinion Form Received

NOTES - Medical Opinion Form Received

---

Script Files/NOTES/NOTES - Fraud Info

fraud info

---

Script Files/MEMOS/MEMOS - OVERDUE BABY

Creates a SPEC/MEMO to send when someone has not reported the birth of their baby/end date. Also creates a CASE/NOTE, and optional TIKL.

MEMOS - OVERDUE BABY

---

Script Files/NOTES/NOTES - CAF.vbs
Script Files/NOTES/NOTES - CLIENT CONTACT.vbs
Script Files/NOTES/NOTES - COMBINED AR.vbs
Script Files/NOTES/NOTES - CSR.vbs
Script Files/NOTES/NOTES - EMERGENCY.vbs
Script Files/NOTES/NOTES - GRH - HRF.vbs
Script Files/NOTES/NOTES - HC RENEWAL.vbs
Script Files/NOTES/NOTES - HCAPP.vbs
Script Files/NOTES/NOTES - HRF.vbs
Script Files/NOTES/NOTES - LTC - 1503.vbs
Script Files/NOTES/NOTES - LTC - RENEWAL.vbs
Script Files/NOTES/NOTES - VERIFICATIONS NEEDED.vbs

Affected scripts
CAF
CAR
CC
EMER
GRH HRF
HRF
HCAPP
HC renewal
LTC 1503
LTC Renewal
Verifications needed.
Ran into issues with dialog editor and CSR. Will try to add checkbox
soon.

adding AREP boxes to scripts

---

Script Files/MEMOS/MEMOS - OVERDUE BABY.vbs
Script Files/NOTES/NOTES - CHANGE REPORT FORM RECEIVED.vbs
Script Files/NOTES/NOTES - DRUG FELON.vbs
Script Files/NOTES/NOTES - FRAUD INFO.vbs
Script Files/NOTES/NOTES - GAS CARDS ISSUED.vbs
Script Files/NOTES/NOTES - LTC - TRANSFER PENALTY
Script Files/NOTES/NOTES - SHELTER FORM RECEIVED.vbs

This should solve some bugs with the new scripts, for reasons I cannot explain in any capacity at the moment.

Change maxis ref in nav to screen

---

Script Files/NOTES/NOTES - DRUG FELON.vbs
Script Files/NOTES/NOTES - LTC - TRANSFER PENALTY.vbs
Script Files/NOTES/NOTES - SHELTER FORM RECEIVED.vbs

Removed DIMs to test to see if that's the reason it doesn't work. If this is correct, it could be that we are DIMing within the run_from_GitHub function and that for some reason that does not fly. More research may need to be done on the subject...

More bug fixes

---

Script Files/NOTES/NOTES - CHANGE REPORT FORM RECEIVED.vbs
Script Files/NOTES/NOTES - GAS CARDS ISSUED.vbs

It appears that some of the DIMing isn't working well with the "run_from_GitHub" function.

Removed DIM'd variables

---

Script Files/DAIL/DAIL - NEW HIRE.vbs
Script Files/NOTES/NOTES - LTC - TRANSFER PENALTY.vbs

Baseline date logic updated to require date in MM/DD/YYYY format to ensure that lookback period is accurate

Ltc transfer penalty

---

Script Files/NOTES/NOTES - LTC - INTAKE APPROVAL.vbs

Lookback period is calculating correctly by requiring the user to enter
the baseline date with date format of MM/DD/YYYY

Issue #483 resolved

---

Script Files/MEMOS/MEMOS - MFIP ORIENTATION.vbs

Updates the memo / note to list the household members needing to attend.  Issue #530.

Enhancement to list household members

---

Script Files/MEMOS/MEMOS - SNAP E&T LETTER

Sends A SNAP E&T Referral Letter and case notes.  Similar function / dialog to MFIP Orientation letter for choosing address.  (Thanks @theVKC). Resolves #87 (just a few months later than planned).  Fully functional now, and ready for future enhancements from Ilse Ferris for #523 ABAWD script.

Create MEMOS - SNAP E&T LETTER

---

BULK - MISC NON-MAGI HC DEDUCTIONS

This is working well now.  Thanks @RobertFewins-Kalb for the help.  I really appreciated it!

BULK - NON-MAGI HC DEDUCTION

---

Script Files/MEMOS/MEMOS - SNAP E&T LETTER.vbs

Bugfix for dialog error

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs
Script Files/MEMOS/MEMOS - SNAP E&T LETTER.vbs

MEMO script now includes most county addresses in an array so that each county that provided address can have a customized drop down menus that autofills the address.  hennepin co users will have the contact info autofill along with contact phone numnber.  also updated dialog boxes to 2 dialogs" autofill dialog and manual address input dialog.  Also added MsgBox reminding worker to update WREG panel with FSET orientation date if not already done.

Snap E AND T MEMO

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Pope County added to list.  Updated Douglas Co addr as suite # was
incorrect.  Also updated dialog boxes to not EDIT verbiage in the edit
boxes, and adjusted the size of contact name and phone edit boxes. ANNNNDDDD let's try this again....

SNAP E AND T

---

Script Files/NOTES/NOTES - HC RENEWAL.vbs

Removed the checkbox for SNAP_CSR_check from dialog.

Update NOTES - HC RENEWAL.vbs

---

Script Files/NOTES/NOTES - HC RENEWAL.vbs

Here's what I changed:
1. Droplist box for recert_status contains a "select one" now.
2. Replaced logic for case_number grabbing with custom function.
3. Fixed indenting to be a tab instead of spaces.
4. Replaced logic for check_for_MAXIS with the custom function (instead of manual process).
5. Removed ERRR_check, this has been added to navigate_to_MAXIS_screen.
6. Adjusted capitalization where appropriate.
7. Simplified do...loop with cancel_confirmation and proceed_confirmation functions.
8. Added new function for start_a_blank_case_note.
9. Modified case note functions to match newer conventions.
10. Removed SNAP_CSR_check from the case note area. Not even an option anymore.

Made a variety of minor enhancements and removed the checkbox we don't need

---

Script Files/NOTES/NOTES - LTC - 5181.vbs

It should now work correctly and with logic for required fields. It
involves a TON of do...loops. @IlseFerris, I can explain this later if
you'd like. :)

Fixed the dialog logic entirely

---

Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER LOOK UP.vbs
Script Files/NAV/OTHER NAV/NAV - Phone Number Look Up

Corrected incorrect naming conventions

Phone search

---

Script Files/NOTES/NOTES - EMPLOYMENT PLAN OR STATUS UPDATE

Create NOTES - EMPLOYMENT PLAN OR STATUS UPDATE

---

Script Files/DAIL/Cola Auto Approved

Script will navigate to GRH/MSA/FS "Auto approved COLA" DAIL messages, copy them into case notes, delete the DAIL and create a report of all COLA messages.
Sorry I thought you wanted this in BETA.

Cola Auto Approved

---

Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER LOOK UP.vbs

Fixed complete phone logic for 2 and 3
added code to check AREP panel per worker suggestion.

Phone search patch1

---

Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER LOOK UP.vbs

Fixed few logic issues, added AREP functionality, fixed stat name issue.

Phone search 3

---

Script Files/MEMOS/MEMOS - GRH OP CL LEFT FACI.vbs
Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Basic MEMO script.  Dialog allows user to enter OP address & 6 fields for OP dates and amounts.  Fields for discovery and established date, gives user the option to send the OP to DHS or enter their own county/agency addr. Will also give the user the option to set a 30 day TIKL to recheck if necessary.  All items in the dialog will then be case noted, and a SPEC/MEMO sent.

MEMOS - GRH OP CL LEFT FACI

---

Script Files/BULK/BULK - COLA AUTO APPROVED DAIL NOTER.vbs

Made a few minor changes needed for consistency:
1. File didn't end with VBS, or was all caps in file name.
2. This script is best described as a BULK script instead of a DAIL
script.
3. Updated FuncLib block.
4. Adjusted indenting on a few lines.
5. Removed DIMing and Option Explicit (because it's being run from
another script).
With this, we should be good to release on this script. :)

Replaced COLA auto approved with BULK vbs file

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Updated Blue Earth information, commented out dimmed variables

Committing to pull request for state wide release

---

Script Files/MEMOS/MEMOS - APPOINTMENT LETTER.vbs
Script Files/NOTES/NOTES - HC RENEWAL.vbs

Bringing BETA change back to master

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs
Script Files/NOTES/NOTES - DOCUMENT NOTING MENU.vbs

This pull request contains two updates:
1. Improved array handling for the new SNAP E and T memo.
2. The new document noting memo, which will save space and condense issues on the notes menus.
This should resolve #498.

Adding june 2015 scripts

---

Script Files/NOTES/NOTES - CLIENT CONTACT.vbs

This should be helpful. General client contact updates. Booyah!

Resolved #526

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

updated dialog with policy reference

committing to pull request

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Updated snap e and t with blue earth

---

Project Mosquito/README.txt

This is making the new folder. :)

Creating new folder

---

Project Mosquito/Income Dialog.vbs

This is the dialog for entering income for any household members that are entered on the household member dialog.

Income Dialog.vbs

---

Project Mosquito/Shelter Dialog.vbs

This is the dialog used to enter client's shelter information in the screening tool script.

Shelter Dialog.vbs

---

Project Mosquito/asset dialogue.vbs

This would be used for screening tool for assets

asset dialogue.vbs

---

Project Louie/ACTIONS - CS Disregard FIAT.vbs

adding 5/28/15 work from Charles, Gay, Ilse.

Life with louie

---

Script Files/NOTES/NOTES - LTC - 5181.vbs

Commented out MAXIS_dialog_navigation function as it seemed to be not used in the script and causing errors.

5181 patch

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

Approved programs update

---

Project Louie/ACTIONS - CS Disregard FIAT.vbs

BIG update...
The script builds Household_array. The map of the array starts on line 152.
The script is build to only look at panels for household members that are relevant. For example, when looking at UNEA, the script only looks at UNEA for those household members that are children on PARE 01.
The script is programmed with a hard break on ELIG/DWP when FIATing to make sure that it does not jump ahead of MAXIS and dump information that is not relevant to the case.
MFIP is a much simpler ordeal.
Possible enhancement opportunity is multiple benefit month handling. That requires restructuring the script to pull the active or pending cash program off STAT/PROG to enable the script to handle the transition from DWP to MFIP. Currently, the script looks at CASE/CURR to determine the CASH …

Project louis part 1

---

Project Louie/ACTIONS - CS Disregard FIAT.vbs
Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

Retooling the case noting function to accommodate the MFIP housing grant. Simple fix

Mfip housing approved progs

---

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs

The script now has documentation.
The script is now handling the disregard limit effectively.
The script is now NOT using scientific notation.
The script is now under control.
Order has been restored to the universe and my email can stop blowing up.
The script includes message boxes to inform the user of what it is doing.

Cs disregard fiater now with extra strength documentation

---

Script Files/NOTES/NOTES - CSR.vbs

(1) Removed CANCEL and CASE NOTE dialogs
(2) Replaced CANCEL and CASE NOTE dialogs with MsgBox("...", vbYesNo)

Csr remo cancel and case note dialogs

---

Script Files/NOTES/NOTES - CAF.vbs

Two updates...
(1) Added Addendum to the droplist of CAF types
(2) Added TIKL to prompt the worker to APPL an incomplete CAF reinstate for CASH/SNAP

Caf updates

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

script_end_procedure commented out

---

Script Files/BULK/BULK - FIND MAEPD MEDI CEI.vbs

This script looks through your REPT/ACTV to create a list of clients that are active on MA-EPD and eligible for Medicare Part B Reimbursement through the county.

Bulk find maepd medi cei

---

Script Files/NOTES/NOTES - LTC - INTAKE APPROVAL.vbs

* added proceed_confirmation
* updated case note header, & to case note if no * spenddown exists
* updated old custom functions
* updated dialog to have more specific MsbBox's    for errors.  
* Updated case note to note both the lookback period start and end date. 
* Updated MsgBox if date is not MM/DD/YYYY format.
* Added in other custom functions (cancel_confirmation)

Ltc initial approval fix

---

Script Files/NOTES/NOTES - LTC - INTAKE APPROVAL.vbs

* added proceed_confirmation
* updated case note header, & to case note if no * spenddown exists
* updated old custom functions
* updated dialog to have more specific MsbBox's    for errors.  
* Updated case note to note both the lookback period start and end date. 
* Updated MsgBox if date is not MM/DD/YYYY format.
* Added in other custom functions (cancel_confirmation)

pulling directly into BETA for testing--critical bug

---

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

Resolves #646.  The script will now bypass privileged cases and give the worker a list of the ones it skipped in a msgbox at the end.

Privileged case handling added

---

Script Files/NOTES/NOTES - CSR.vbs

Added in ABAWD edit box. However this did bring back the 65 item limit for the CSR. I added a new spooky item to work around it. the dialog can no longer be edited in dialog editor and will need to be done manually or by taking out enough items and re adding them later. #698

Csr abawd match

---

Script Files/MEMOS/MEMOS - DUPLICATE ASSISTANCE WCOM.vbs

Added verbiage from state

---

Script Files/NOTES/NOTES - LTC - ASSET ASSESSMENT.vbs

.  There are up to 8 screens available, and time permitting will be updated with an array in the future.  also updated the case note to NOT case note empty blank asset spots into person or case note, updated old functions with new custom functions.

Updated to read up to 4 total marital asset screens & note them

---

Script Files/NOTES/NOTES - LTC - INTAKE APPROVAL.vbs

The script was calling the wrong function. This was causing the error reported by @khiestand

Ltc intake approval fix

---

Script Files/BULK/BULK - COLA AUTO APPROVED DAIL NOTER.vbs

Won't read same message over and over when bulking
won't set cursor wrong after a maxis check
allows for INFO messages since GRH and MSA are info messages.

Bulk cola fix

---

Script Files/NOTES/NOTES - LTC - COLA SUMMARY 2015.vbs

Looks like some formatting for the header was included in the change as well.

Updated 01/15 to 07/15

---

Project Krabappel/KRABAPPEL FUNCTIONS FILE.vbs

Combined with pull #731, Fixes #573

Child under 1 handling added to EMPS

---

Project Krabappel/BULK - project Krabappel.vbs

Can now approve family cash packages for lots of months!

add handling for DWP-MFIP transition to approval

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

Resolves #733.  Also improved logic for reading correct approval versions, and updated to current functions throughout.

Allows worker to choose number of months of MONY/INQX to show

---

Script Files/NOTES/NOTES - LTC - COLA SUMMARY 2015.vbs

missed one more 01/15, scoured rest of script to make sure I caught rest. Please pull into beta/release upon return. Thanks!

Missed one 01/15

---

Script Files/NOTES/NOTES - FSET SANCTION.vbs

This should resolve issue #675

NOTES - FSET SANCTION

---

Script Files/NOTES/NOTES - LTC - INTAKE APPROVAL.vbs

Catching release up with BETA

---

Script Files/MEMOS/MEMOS - APPOINTMENT LETTER.vbs

I believe the following issues are resolved:
* Resolved #96.
* Resolved #666.
* Resolved #762.
* Resolved #768.
* Resolved #770.
See https://github.com/theVKC/VKC-Script-Changes/commit/aa43adb106c2a8bb8df9ec56a93a47b03070ee26 for details.

Appt letter june enhancements

---

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs

dialog revision

---

Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs
Script Files/NOTES/NOTES - MAIN MENU - H-Z.vbs

Updated both NOTES power pads with my scripts, removed 'NEW 06/15' from both power pads as well
FSET SANCTION: A case note template for imposing or resolving an FSET sanction which will also update the MAXIS WREG panel.
SNAP CASE REVIEW: A basic case note template for SNAP reviewers to use that will case note whether a SNAP quality review was correct or incorrect

Snap quality second check

---

Script Files/BULK/BULK - MAIN MENU.vbs

Updated the BULK main menu with extra buttons (and re-arranged appropriately)...
* DAIL Report -- script builds a list with case numbers, client names, DAIL types, DAIL dates, and DAIL messages
* ADDR Report -- script builds a list of case numbers, client names, and living address (can be run for individual workers or entire agency)
* MA-EPD/MEDI CEI Look-Up -- script builds a list of all cases and clients active on MA-EPD and eligible for Medicare Part B reimbursement through the agency (rather than an MSP).

Bulk menu update

---

Script Files/DAIL/DAIL - BNDX SCRUBBER.vbs

Adding check for INFC agreement

---

Script Files/NOTES/NOTES - FSET SANCTION.vbs
Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs

FSET sanction ready.  Custom function added.  FuncLib updated.

Fset sanction 

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

Added safeguard to prevent loss of data when accidentally selecting "none" for burial agreement type. Updated a few older functions to newer ones.
#792

Adding new logic/udpating old

---

Script Files/BULK/BULK - CHECK SNAP FOR GA RCA.vbs
Script Files/BULK/BULK - MAIN MENU.vbs

New script that builds a list of all cases that are active on SNAP & GA or RCA. The script looks at current month plus one, goes to the most recently approved version, and determines if the monthly grant is different from the amount FIAT'd into SNAP. 
If the case is at review, the script will note that in the Excel file.
If the case is set to close, the script will note that in the Excel file.

NEW SCRIPT -- CHECK SNAP FOR GA/RCA

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
Script Files/NOTES/NOTES - CAF.vbs
Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs
Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs

Notice reminders

---

Script Files/NOTES/NOTES - SNAP CASE REVIEW.vbs

"call" was missing from a function

CRITICAL BUG FIX

---

Script Files/NOTES/NOTES - SNAP CASE REVIEW.vbs

Added @IlseFerris' critical bug fix to release branch.

Update NOTES - SNAP CASE REVIEW.vbs

---

Script Files/ACTIONS/ACTIONS - SEND SVES.vbs

@RobertFewins-Kalb, please pull request critical bug fixes into RELEASE in addition to master, and BETA if we are not close to a BETA release. I am making one tonight, so we're good on that count.

Updating with @RobertFewins-Kalb's critical bug fix

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

Also corrects an occasional issue with unapproved versions being read

Added handling for MFIP housing grant

---

Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs

same deal as with the SNAP CASE REVIEW script, just thought the magic
would happen. #BIGFAIL

Critical bug for FSET sanction

---

Script Files/NOTES/NOTES - MAIN MENU.vbs
Script Files/REDIRECT - NOTES - 0-G.vbs
Script Files/REDIRECT - NOTES - H-Z.vbs

Creating consolidated NOTES main menu with alpha-split tabs

Create new notes main menu

---

Script Files/ACTIONS/ACTIONS - SEND SVES.vbs

Please do this...BETA agencies do not have the fix yet

Update ACTIONS - SEND SVES.vbs

---

Script Files/NOTES/NOTES - EXPEDITED SCREENING.vbs

Added verbiage to state that the income, assets and shelter costs fields
will default to $0 if left blank.  Added new functions, took out old
functions.  cleaned up other coding and the dialog.  
Tested, and it's looking good!

several updates for OP DOUBTFIRE and more

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

Bug fix for handling of MFIP housing grants

---

Script Files/NOTES/NOTES - LTC - 1503.vbs

removed old functions, added new functions.  Cleaned up dialogs, and old coding with new functions.  Also added in more logic if case is an ICF-MR and RTC which was not in here.  also switched the order of the HCMI and FACI panel updates so that workers can review the faci panel.
this resolves issue #541

1503 update

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Adding the four buttons that were missing because I'm stupid...
* Change Report Form Received
* Docs Received
* Medical Opinion Form Received
* Shelter Form Received
Resolves #821

Update NOTES - MAIN MENU.vbs

---

Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs

Added Call create_panel_if_nonexistent() function

---

Script Files/NOTES/NOTES - VERIFICATIONS NEEDED.vbs

Added BURIAL to the OTHER editbox, and added Veteran's info as an
editbox in the dialog.  Also cleaned up old functions and updated new
functions.

committing to pull request: added edit boxes

---

Script Files/NOTES/NOTES - LTC - INTAKE APPROVAL.vbs

cleaned up dialog a little, removed older calculations that have been
since replaced by custom functions.

Updated old functions, deleted repeated info in case note

---

Script Files/NOTES/NOTES - LTC - APPLICATION RECEIVED.vbs

Added checkboxes and droplist to the dialog.  added functionality to update PND2 to 'client delay', and set a 45 or 60 day TIKL.  Also cleaned up script, and replaced old functions.
This resolved issue #642

Ltc app rec

---

Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs

accounts for number of JOBS = 1 ... #dumb

Update ACTIONS - PAYSTUBS RECEIVED.vbs

---

Script Files/NOTES/NOTES - LTC - MA APPROVAL.vbs

So you didn't like MAXIS_MAXIS?  The system so nice I named it twice?
Also cleaned up script and old functions.

Ma approval-added paperless IR option

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

Memos button fix

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

Update MEMOS - MAIN MENU.vbs

---

Script Files/NOTES/NOTES - REIN PROGS.vbs

This a case noting script that workers can use to note details about reinstatement of programs.

NOTES - REIN PROGS.vbs

---

Script Files/NOTES/NOTES - LEP - EMA.vbs

This is a case note function that will allow workers to process EMA mnsure applications in Maxis

NOTES - LEP - EMA.vbs

---

Script Files/NOTES/MFIP SANCTION CURED.vbs

This is a case note script for a financial worker to note the details of a MFIP sanction being cured.

NOTES - MFIP SANCTION CURED.vbs

---

Script Files/NOTES/NOTES - DOCUMENTS RECEIVED.vbs

committing to pull request.  Tested and good to go.
Resolves issue #828

updated doc's rec'd to reflect verifs requested format

---

Script Files/BULK/BULK - ADDRESS REPORT.vbs
Script Files/NOTES/NOTES - DOCUMENTS RECEIVED.vbs

wrong variable being called.  Updated and tested, working good.
Also made a custom function :)
Will also pull into BETA and RELEASE

Bulk addr critical bug

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

removed elitist functionality allowing only Hennepin county users to use script (added for testing purposes, but forgot to remove).
Updated dialog verbiage from Select one to Select one... (my personal standard in scripting so I don't forget what I wrote everytime).
Updated case note in include the MEMB # in the header, and the memb name and # in the case note body.
Added LOOPing logic that ensures the MEMB # is a 2 digit number and that a FSET office is not Select one...

Snap e and t update

---

Script Files/MEMOS/MEMOS - GRH OP CL LEFT FACI.vbs

Grh op fix/enchancement

---

Script Files/DAIL/DAIL - BNDX SCRUBBER.vbs

Syntax error with SEP for SSA agreement check.

Update DAIL - BNDX SCRUBBER.vbs

---

Script Files/NOTES/NOTES - LTC - RENEWAL.vbs

This is part of Operation Doubtfire.

Removed the worker_sig, replaced with worker_signature

---

Script Files/NOTES/NOTES - PROOF OF RELATIONSHIP.vbs

This script is for case noting proof of relationship documents received for household members.

New NOTE script for Proof of Relationship documents received.

---

Script Files/NOTES/NOTES - LOBBY NO SHOW.vbs

Script creates a case note when a client no shows to a lobby interview, includes option to send NOMI. @RobertFewinsKalb

New Script for Lobby No Show Note

---

Script Files/NOTES/NOTES - EVF RECEIVED
Script Files/NOTES/NOTES - EVF RECEIVED.vbs

This is a new case note script for when an EVF has been received. @theVKC @RobertFewins-Kalb

Create new file

---

Project Krabappel/BULK - project Krabappel.vbs

Updates...
* Removed call to local Krabappel FuncLib (those functions have been pulled into BZS FuncLib)
* Modified calling from Excel to work with data validation
* Added functionality to create dates of birth other than 01/01 (resolves #188 )
* Added functionality to shift date of application to CM minus X months (resolves #450 )
* Can FIAT GA amount into SNAP

Update BULK - project Krabappel.vbs

---

Script Files/MEMOS/MEMO - SIGNIFICANT CHANGE.vbs
Script Files/MEMOS/MEMOS - SIGNIFICANT CHANGE.vbs

Case note for Significant Change. Sends Spec/memo for denial. Sends Tikl for future month request. Few more safeguards needed. 
Currently Denial check box can be checked when choosing any significant change status.

Significant Change New Script

---

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs

adds the list of verifs needed to SNAP/CASH denial notices for no proofs if requested
also updated old functions

Adds Worker comments to notices #754

---

Script Files/NOTES/NOTES - LTC - 1503.vbs

resolves issue #895, critical bug fix pull into RELEASE

Update NOTES - LTC - 1503.vbs

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

Updating functions to include new ones.

---

Script Files/NOTES/NOTES - PREGNANCY REPORTED.vbs

This is a case noting template that case notes details of a pregnancy reported to the agency.  It will also update the STAT/PREG panel for that member.
Having some troubles around line 144, also, when I run this in training region the case number doesn't auto-populate into the dialog.
Issue #912

NOTES - PREGNANCY REPORTED.vbs

---

Script Files/NOTES/NOTES - PREGNANCY REPORTED.vbs

Inserted additional safeguards.
Simplified DO/LOOP around dialog.
Fixed problematic function calls.

Update NOTES - PREGNANCY REPORTED.vbs

---

Script Files/NOTES/NOTES - LTC - TRANSFER PENALTY.vbs

Also updated dialogs, new FuncLib line from Op Doubtfire, added
auto-fill functionality and made dialogs mandatory

Transfer penalty bug fix

---

Script Files/NOTES/NOTES - MAIN MENU - 0-G.vbs
Script Files/NOTES/NOTES - MAIN MENU - H-Z.vbs
Script Files/REDIRECT - NOTES - 0-G.vbs
Script Files/REDIRECT - NOTES - H-Z.vbs

This time, it's personal. This fixes the issue with the script calling run_from_GitHub after calling run_from_GitHub and not connecting to a script file.

Main menu fix again

---

Script Files/NOTES/NOTES - LTC - RENEWAL.vbs

Do loop was still looking for worker_sig after it was changed to worker_signature

Worker_sig update

---

Script Files/NOTES/NOTES - LTC - MA APPROVAL.vbs

Spelling error on line 289

---

Script Files/NOTES/NOTES - EVF RECEIVED.vbs

Added dialog for gathering and confirming case number

Update NOTES - EVF RECEIVED.vbs

---

Script Files/NOTES/NOTES - HH COMP CHANGE.vbs

Fixed case number bug, Tweaked dialog, Tweaked the way things are added to case note to read a little easier, changes do/loop to include err_msg format. Tested locally.
#904

fixed bug/updates

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Apparently the "i" was after the "e". :P
Also, more seriously, updated Pine County's address. This is critical as it's in use right now, so I will directly pull into all three branches.
Resolves #963.

Added new address and updated spelling of "thief"

---

Script Files/MEMOS/MEMOS - SIGNIFICANT CHANGE.vbs

Thanks for your help guys! @theVKC @RobertFewins-Kalb @IlseFerris
Significant Change script includes a spec/memo denial letter that is automatically sent if you are denying the request and can put out a Tikl if client is requesting for a future month. 
The script is written with the new Do..Loop process which brings up an error message if a mandatory field is not entered.

Update MEMOS - SIGNIFICANT CHANGE.vbs

---

Script Files/NOTES/NOTES - FRAUD INFO.vbs

added combobox for overpayment status, added notes text box explaining ; carriage return option, added err_msg logic replacing loop. cleaned up blank lines  #905

Enhancement

---

Script Files/BULK/BULK - LTC-GRH LIST GENERATOR.vbs

Added DOC (difficulty of care) amount to excel output. #952

Added field

---

Script Files/ACTIONS/ACTIONS - MA-EPD EI FIAT.vbs

Bug fix for cases where job has recently ended and is still needed in maxis but script was reading ____ instead of ""  #970

Bug fix for blank jobs panels

---

Script Files/NOTES/NOTES - SNAP CASE REVIEW.vbs

dialog gives the option to select SNAP or MFIP
grant amount(s) will be auto-filled into the case note
added error handling cases that are UNAPPROVED or if the case is NOT ACTIVE on a program
Resolves issue #955

Snap case review enhancement

---

Script Files/NOTES/NOTES - SUBMIT CASE FOR SNAP REVIEW.vbs

case note template requested by Henn Co workers submitting cases for
SNAP CASE REVIEW.  Companion script to NOTES- SNAP CASE REVIEW.
This resolves issue #973 
I pulled this into 'agency custom' here at Hennepin County, but thought I'd share it for the masses if determined to be helpful.

initial commit

---

Script Files/MEMOS/MEMOS - MNSURE MEMO.vbs

Added logic to allow commenting on multiple HH members and better searching for waiting notices. #961

Adding logic for multi members and waiting notices

---

Script Files/BULK/BULK - FIND MAEPD MEDI CEI.vbs

Added fix to MMIS navigation logic to always get back to RKEY.

Update BULK - FIND MAEPD MEDI CEI.vbs

---

Script Files/NOTES/NOTES - LTC - MA APPROVAL.vbs

Added 'special header' droplist which user can select NONE, HRF or
PAPERLESS IR.  Also removed old MAXIS_dialog_navigation.
This resolves issue #874

HRF option enchancement request

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Added NOTES - MAIN MENU scripts

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Also updated the FuncLib path (Op Doubtfire)
Upated Check for MAXIS TRUE to FALSE
added Aitkin county to be an 'autofill county'

added Aitkin Co to the party

---

Script Files/NOTES/NOTES - EMPLOYMENT PLAN OR STATUS UPDATE.vbs

Fixes case noting / dialog bug with Status update portion

Bugfix NOTES - EMPLOYMENT PLAN OR STATUS UPDATE.vbs

---

Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs

moved MAXIS background check ahead of nav to STAT/BUDG

critical bug---issue #1004

---

Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs

bug fix issue #1004

---

Script Files/NOTES/NOTES - LTC - MA APPROVAL.vbs

* updated script to navigate to the correct ELIG/HC footer month and
year
* Error handling: if case is not L, S,  or B budget, script will end
with message informing the worker to use the Approved programs script
instead of LTC MA approval script
* Updated approval dialog to update with "$0" if recip amt, income or
deductions do not exist
* updated to have worker_signature to be mandatory field
* updated PAPERLESS IR to Paperless IR (which was causing S and B
budgets to not have a case note header.

BUG fix for LTC MA approval issue #1008

---

Script Files/NOTES/NOTES - LTC - MA APPROVAL.vbs

* updated script to navigate to the correct ELIG/HC footer month and
year
* Error handling: if case is not L, S,  or B budget, script will end
with message informing the worker to use the Approved programs script
instead of LTC MA approval script
* Updated approval dialog to update with "$0" if recip amt, income or
deductions do not exist
* updated to have worker_signature to be mandatory field
* updated PAPERLESS IR to Paperless IR (which was causing S and B
budgets to not have a case note header.

Bug fix for issue #1008

---

Script Files/NOTES/NOTES - MNSURE RETRO HC APPLICATION.vbs

This is a case noting template that details the information about a MNSure retro health care request that a financial worker must process in MAXIS/MMIS. The script will note the following details: curam case number, app rec'd date, gap month, number of retro months requested, if hc closed within 120 days, who coverage is requested for, hc app status, verifs needed, other comments, actions taken, if a tikl was created and if MMIS was updated.  The script then navigates to DAIL/WRIT and puts a date 10 days out for the worker to then type what they requested and any other notes there.
Issue #875
Thanks!

NOTES - MNSURE RETRO HC APPLICATION.vbs

---

Script Files/BULK/BULK - RETURNED MAIL.vbs

Updated dialog box.
Updated pre-script warning box. 
Added MailType array.
Added counter to compare between arrays.
Reworked noting and TIKLing to If/Else around MailType array.  
Changed verbage in case note and TIKL. 
Added logic to create error message box listing any case numbers that the script failed on. (Invalid case numbers or privileged)
Updated some functions.
#397

Added forwarding mail functionality.

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

Adding a fix to address an autofill problem reported.

Update NOTES - APPROVED PROGRAMS.vbs

---

Script Files/NOTES/NOTES - CAF.vbs

added email to app rec'd options

---

Script Files/NOTES/NOTES - DOCUMENTS RECEIVED.vbs

Defaulted focus to No since most cases are not LTC.
#1024

refocused VByesnocancel

---

Script Files/BULK/BULK - MAIN MENU.vbs

Added button and link for BULK - PDED LIST GEN.vbs
Added link for BULK - FIND PANEL UPDATE DATE.vbs

Added button and 2 links to BULK MENU

---

Script Files/BULK/BULK - PDED LIST GEN.vbs

This script will create a list from an x-number's REPT/ACTV that can be used for tracking the following information on PDED:
* Pickle Disregard
* DAC Disregard
* Unearned Income Disregard
* Earned Income Disregard
* Guardianship Fee
* Rep-Payee Fee
* Shelter/Special Needs
The script will remove rows that are blank.

Create BULK - PDED LIST GEN.vbs

---

Script Files/NOTES/NOTES - EXPEDITED SCREENING.vbs

Updated HEST amounts in EXP screening script

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

#1056 Turns out the instructions came through on the wiki as well so we are good to start beta testing on this one.

Adding back in CS fiater

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

adding back in cs fiater logic

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

yep, that's right.
Also resolves issue #1055

added functionality to update WREG with appt date

---

Script Files/NOTES/NOTES - CITIZENSHIP-IDENTITY VERIFIED.vbs

Duplicate dialogs were in the script (only 1 needed).
Old maxis checking functions removed from DO LOOP

critical bug fix in master branch only

---

Script Files/NOTES/NOTES - MEDICAL OPINION FORM RECEIVED.vbs

Added last exam date field
reorganized case note a bit
#1063

Enhancement adding exam date/misc

---

Script Files/NOTES/NOTES - HCAPP.vbs

variable for MMIS_update_checkbox was missing updated in case note section (per Ilse I could go ahead and knock this one out quickly.)  #1016

minor bug fix

---

Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/MEMOS/MEMOS - MAIN MENU.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

ACTIONS was in a different pull as there was a bug
This resolves issue #1021

updated SIR instruction addresses for BULK, MEMOS, and NOTES

---

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs

Fix to MFIP fiating procedure

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

* basically 2 buttons and associated text were overlapping.  updated to
create room for both.  
Also updated web address for instructions on SIR
for ACTIONS scripts.

bug fix for CS fiater

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

*updated SIR instruction web address
* moved 2 of the script buttons and text so they do not overlap

Updated ACTION MAIN MENU button, bug fix in RELEASE branch

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

updated MEMO's button in RELEASE branch

---

Script Files/BULK/BULK - MAIN MENU.vbs

Updated SIR instructions web address--release branch

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

sir address for script instructions
issue #1021

updated notes main menu in release branch

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Resolves #832, plus adds ES database logic, plus replaces all the code below the functions library block because somewhere along the way this got replaced with MFIP sanction cured code.

Enhance / fix MFIP Sanction Cured

---

Script Files/BULK/BULK - REPT-PND2 LIST.vbs

Now, the comparison function should work. @TRISOR should get credit for the 1 line :)

Defining "is_not_blank_excel_string"

---

Script Files/NOTES/NOTES - CAF.vbs

#1029
I updated the DO loop to account for longer than 10 digit datestamps and warning the worker on the dialog they made the error on. 
updated function block
tikl function not used (did not mess with Tikling already hard coded in there as it works already and is designed around pre functions)
spec/memo not updated, does not spec memo
write_variable_in_case_note seems to be already updated
check_for_maxis, already updated
nagivate_to_maxis, updated to new function
MAXIS_dialog_nav, already updated

Update NOTES - CAF.vbs

---

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs

#1031
Updated do loop, left 2nd do loop alone as it has very complex requirements involving multiple variables with multiple combinations of values. As such it really doesn't fit into the err_msg structure.
updated navigate to maxis functions
updated cancel confirmations
updated function library block

Update ACTIONS - TRANSFER CASE.vbs

---

Script Files/NOTES/NOTES - LTC - 5181.vbs

#1030
Updated function block
updated do loops where it was feasible to include new err_msg logic
added cancel confirmation

Update NOTES - LTC - 5181.vbs

---

Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/BULK/BULK - REPT-INAC LIST.vbs

BULK INAC List script add(menu update as well)

---

Script Files/NOTES/NOTES - HCAPP.vbs

Fix for footer month issue

---

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs

Bug fix for reading PARE incorrectly.

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

*updated DO LOOP with new err_msg standard
*added error handling to prevent users from selecting a date in the past
* made the AM_PM droplist a mandatory field
* changed script to end after saving the SPEC/LETR
* updated the message box  at the end of the script informing the user
that the orientation letter can be viewed in SPEC/WCOM

SNAP E & T multiple enhancements.

---

Project Krabappel/BULK - project Krabappel.vbs

simplying loop for REI'ing SNAP

---

Script Files/NAV/NAV - POLI-TEMP.vbs

I've edited it a little bit, tested, changed the dialog box so that I'm not complicating it as much as I need it to be (missing values & etc).  This should allow the user to navigate to Index and TABLE both ways; before you have to exit out back to SELF manually to use the script again.

Update NAV - POLI-TEMP.vbs

---

Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs

The script is now grabbing the MAXIS case number and using navigate_to_MAXIS_screen to get to STAT/JOBS

Fixing navigation issue with DAIL-CSES NEW JOB

---

Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs

The script was not grabbing the case number but was using navigate_to_MAXIS_screen.

Fixing navigation issue on CSES New Job DAIL

---

Script Files/NOTES/NOTES - LTC - APPLICATION RECEIVED.vbs

case_number_dialog was not closed.
Closed dialog and added err_msg handling for the dialog

Closing dialog in LTC Application Received

---

Script Files/NOTES/NOTES - LTC - APPLICATION RECEIVED.vbs

closed case number dialog
added err_msg handling to second dialog

fixes to LTC Application Recv'd

---

Script Files/NOTES/NOTES - COMBINED AR.vbs

This is only effecting the BETA and MASTER branches as this was a Doubtfire update. Also removed extra blank spaces.

Footer month not pulling into dialog (BETA & MASTER BRANCHES only)

---

Script Files/NOTES/NOTES - COMBINED AR.vbs

autofill date fix for Combined AR script in BETA branch

---

Script Files/NOTES/NOTES - HCAPP.vbs

Footer month issue fix

---

Script Files/NOTES/NOTES - HCAPP.vbs

#1139 whoops. I thought I had already.

Fixing footer month + 1 issue

---

Script Files/NOTES/NOTES - EXPEDITED SCREENING.vbs

if the case appear exp, and the client is known to the EBT system.

updated case EXP SCREENING to read NOT able to get EBT card

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

variable name incorrect.  Fixed in Release.

REIN_PROGS_button critical bug

---

Script Files/BULK/BULK - REPT-REVS LIST.vbs

Theoretically simple update to EMReadScreen Cash_Status to accomodate differing MAXIS screens.

Update BULK - REPT-REVS LIST.vbs

---

Script Files/NOTES/NOTES - GAS CARDS ISSUED.vbs

Edited script to include amt given today and amt given year to date in the subject/first line of the case note.  Also added field for worker to enter in the gas card numbers if they wish.
This enhancement resolves Issue# 1144

Update NOTES - GAS CARDS ISSUED.vbs

---

Script Files/NOTES/NOTES - HCAPP.vbs

resolves issue #1177
determining footer_year from date

cleaning up my mess on HCAPP footer_month

---

Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs

The script was getting stuck navigating back to DAIL. Now the script does everything it needs to do with updated functions.

Updating navigation functionality

---

Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs

Updated navigation functionality in script with shiny new ones. The script was getting stuck on SELF.

Replaced dated navigation functions

---

Script Files/NOTES/NOTES - APPLICATION RECEIVED

Case notes when a request for programs has been received and pended. Option to have the script transfer the case to assigned worker.

Create NOTES - APPLICATION RECEIVED

---

Script Files/NOTES/NOTES - INCARCERATION.vbs

This is a new case noting template script that Financial workers can use to note the details of a client incarceration reported to the agency.  It will note the HH member that was incarcerated, the incarceration start date, the incarceration location, the anticipated release date if known, the facility type, how the info was received, probation officer info if known, actions taken, other notes/comments, if STAT/FACI was updated, and if a TIKL was created to check for a release date.  The script will check to see if the HH member already has 5 FACI panels and notify the Financial Worker to clean them up before proceeding.  The script has the ability to update the STAT/FACI panel for the HH member incarcerated, completing the Facility name, Facility type, FS Eligible with an N, Date In, …

NOTES - INCARCERATION.vbs

---

Script Files/ACTIONS/ACTIONS - FSET SANCTION.vbs

changed name to ACTIONS - FSET SANCTION

deleting NOTES - FSET SANCTION

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs
Script Files/MEMOS/MEMOS - POSTPONED WREG VERIFS.vbs

Adding postponed WREG verif MEMO script

---

Script Files/NOTES/NOTES - CAF.vbs

Adding Certain pops app to HC app drop down menu

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Adding button for new script IEVS Notice rec'd

---

Script Files/BULK/BULK - REPT-PND2 LIST.vbs

them shiz was missing. now it be there

reinstating multicounty functionality in BULK - REPT/PND2.vbs

---

Script Files/BULK/BULK - REPT-PND1 LIST.vbs

multicounty handling was not enabled. the function has been reinserted so multicounty agencies can has script

reinstating multicounty functionality

---

Script Files/BULK/BULK - MAIN MENU.vbs

the script is not running the script because the value is not being pulled through the function that creates and loads the dialog

declaring INAC_LIST_button

---

Script Files/NOTES/NOTES - APPLICATION RECEIVED.vbs

Case notes after an application has been received and pended in MAXIS. Option to have the script transfer the case to an assigned worker.

Update NOTES - APPLICATION RECEIVED.vbs

---

Script Files/NOTES/NOTES - CSR.vbs

I did not originally add this...sorry gang

adding notes on income case noting

---

Script Files/BULK/BULK - REPT-INAC LIST.vbs

Removed elitist functionality, changed write screen of worker 3 to write in last 3 digits after x1-- number.
Blip Critical bug resolved allowing users state wide to access the script in their counties.
Resolves issue #1278

Rept inac removed county code in release branch

---

Script Files/NOTES/NOTES - GOOD CAUSE CLAIMED.vbs

DHS-3632 added to the text that has DHS-3627 and DHS-3979 per request. Issue #1157.

Update NOTES - GOOD CAUSE CLAIMED.vbs

---

Script Files/NOTES/NOTES - CSR.vbs

This fix removes the prompt for Worker Signature and adds the Worker SIgnature field on the main dialog.  
Issue #1233

Update NOTES - CSR.vbs

---

Script Files/NOTES/NOTES -  COUNTY BURIAL APPLICATION.vbs

This script case notes when an application is received at the county when a death has been reported and family needs help in paying funeral costs.

Resolves #1239

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Changed chippewa county workforce center name to Montevideo Workforce center
#1254

Updating Chippewa County workforce center name

---

Script Files/NOTES/NOTES - INTERVIEW COMPLETED.vbs

Script to case note when an interview has been completed.
Resolving Issue #1234

Create NOTES - INTERVIEW COMPLETED.vbs

---

Script Files/ACTIONS/ACTIONS - CHECK EDRS.vbs

This is an enhancement of the EDRS Checked script that runs all household members automatically. The script populates a message box with all the household members in the case and the worker can select which members to check. It then inputs the SSN and name for each member and outputs a message box detailing if there was a match for all checked. 
Thank you @CDPotter for helping me with this!!
(Issue # 1251)

Update ACTIONS - CHECK EDRS.vbs

---

Script Files/NOTES/NOTES - MEDICAL OPINION FORM RECEIVED.vbs

This update adds a field for the name of the household member and adds it to the case note.  Also updated the Do loop with the new process (err_msg). 
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/1258

Update NOTES - MEDICAL OPINION FORM RECEIVED.vbs

---

Script Files/BULK/BULK - REPT-INAC LIST.vbs

Removed elitist functionality, changed write screen of worker 3 to write in last 3 digits after x1-- number.
Blip Critical bug resolved allowing users state wide to access the script in their counties.
Resolves issue #1278

Rept inac removed county code in master branch

---

Script Files/ACTIONS/ACTIONS - ABAWD SCREENING TOOL.vbs

Adding new script and updating main menu buttons #1208
BLIP: NOTES - ABAWD SCREENING TOOL: A new script that walks the worker through a screening. It counts the client's counted ABAWD months and provides a flowcharted approach to determining if someone meets an exemption or earned additional months. It will either case note if case is in worker's county or provide a messagebox if not.

Adding ABAWD Screening tool

---

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs
Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

Adding script and updating menu (menu update includes button for previously submitted pull for ABAWD screening tool). Will create instructions for Wiki.
addresses part of #1231
BLIP: New script to be run on a single case to check a single case to see if any possible ABAWD or SNAP E & T exemptions that exist. (Script will check any selected members regardless of their WREG/ABAWD status.)

Adding new script (pull after pulling in ABAWD SCREENING TOOL

---

Script Files/BULK/BULK - REPT-INAC LIST.vbs

And adding multicounty handling

Removing x102 from script

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Adding buttons for County Funeral APP and Interview completed

Adding buttons

---

Project Krabappel/BULK - project Krabappel.vbs

Now with extra strength WF1 referral handling.

Updating WF1 Referral in Krabappel

---

Script Files/DAIL/DAIL - CSES PROCESSING.vbs

Update to restore the previous navigation when the script is completed (will go to DAIL when worker PF3s after script) - in response to issue #1221

Update DAIL - CSES PROCESSING.vbs

---

Project Krabappel/BULK - project Krabappel.vbs

The issue was raised that the button to change wasn't doing what it advertised. I have moved the dialog building to a custom function to allow the script to loop around the dialog, resetting the scenario list, loading the new Excel file, and calling the dialog again with the new list of scenarios.
Tested and working.

Enabling the end user to change the Excel file

---

Script Files/NOTES/NOTES - CSR.vbs

BLIP: Changing OK button to a next on the first dialog to help the user see there is more dialogs to come. 
#1300

Changing OK button to NEXT

---

Script Files/NOTES/NOTES - GRH - HRF.vbs

Resolves issues #1147
FuncLib for ELIG/GRH has been updated to navigate to ELIG/GRH.
Changes GRH pressbutton from ELIG_MFIP_button to ELIG_GRH_button
Change checkbox in dialog from CASH_check to GRH_check

Update NOTES - GRH - HRF.vbs

---

Script Files/NOTES/NOTES - ES REFERRAL.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

Resolves #997 
Blip:  A new script for case noting when a worker refers an MFIP or DWP case to employment services.

Create NOTES - ES REFERRAL.vbs

---

Script Files/NOTES/NOTES - MFIP TO SNAP TRANSITION.vbs

NOTES - MFIP to SNAP error handling when MFIP isn't open

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Century plaza orientations have moved to HSB effective immediately
Updated script to default to MEMB 01. Added the following Hennepin
County specific features:
dialog box to reduce errors for scheduling
Added msgbox with Do Loop that will keep seeking the next available weekday an orientation is scheduled on until it reaches the desired date
script end procedure ending message that informs user to send a specific diamond form
Resolves issue #1349

Critial enhancement SNAP E & T HC addr change effective immediately (Master)

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Century plaza orientations have moved to HSB effective immediately
Updated script to default to MEMB 01.  Added the following Hennepin
County specific features:
* dialog box to reduce errors for scheduling
* Added msgbox with Do Loop that will keep seeking the next available
weekday an orientation is scheduled on until it reaches the desired date
* script end procedure ending message that informs user to send a
specific diamond form
Resolves issue #1349

Critial enhancement SNAP E & T HC addr change effective immediately (Release)

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

Resolves issue #1121 
BLIP: Enhancement to the script that provides a field to enter the program that the burial asset is being evaluated, and fix to the dialog navigation to allow users to navigate back and forth from the first assets dialog though the fourth asset dialog.

Burial assets program header

---

Script Files/NOTES/NOTES - LTC - 1503.vbs

resolves issue #1337
Also cleaned up old stuff that wasn't needed.
BLIP: Bug fix completed to allow user to update the 1503 information in the footer month selected.

LTC 1503 bug fix: to resolve script not updating in footer month selected

---

Script Files/BULK/BULK - DAIL REPORT.vbs

I guess I just busted this out without considering that other people would want to know how it works. Sorry, gang.

Adding comments to BULK-DAIL REPORT.vbs

---

Script Files/NOTES/NOTES - HRF.vbs

Update adds a checkbox to the dialog that gives the option of case noting the elig/fs results for UHFS cases. Issue# 1268

Update NOTES - HRF.vbs

---

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs

Added comments explaining how and why the script handles scientific notation.

ACTIONS - CS DISREGARD FIAT -- comments explaining code

---

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs
Script Files/NOTES/NOTES - HRF.vbs

This does nothing, but I want to keep things in sync.

Merging Robert's comments into BETA

---

Script Files/NOTES/NOTES - HRF.vbs

changed the order of the function calls -- it has to be...
1. cancel_confirmation
2. call check_for_maxis(false)
3. maxis_dialog_navigation
Added err_msg handling
Removed superfluous dialog for case note confirmation

Bug fix to maxis_navigation and cancel_confirmation order

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

This resolves #671. I also created an issue on the installer repo to update this. I set the updated date as the future, because scriptwriters are our future (and it bypasses any planned breakpoints like "you haven't updated your scripts recently enough").

Update SETTINGS - GLOBAL VARIABLES.vbs

---

Script Files/NOTES/NOTES - LTC - 5181.vbs

also cleaned up script (removed blank spaces, updated footer month and
footer year to MAXIS footer month and MAXIS footer year).
resolves issue #995

removed function create_panel_if_nonexistent from LTC 5181

---

Script Files/NOTES/NOTES - CAF.vbs

Added new function call check_for_password which resolves Stearns county's problem with Bluezone version 6+ passwording out.

Resolves #1338

---

Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs

BLIP: Script will now display most recent bills if they exists. This way the worker can review the most recent entries while completing the dialog. 
#1384

Adding functionality to nav to most recent bils

---

Script Files/NOTES/NOTES - CSR.vbs

I did a crappy job of cleaning up the CSR...
the worker_signature logic was not in the appropriate place. Sorry. This has actually been tested.

cleaning up the CSR clean up

---

Script Files/NOTES/NOTES - IEVS NOTICE RECEIVED.vbs

variable "OPTIONS" was checking for "Select one" but the DLB option was "Select"
Resolves #1397

data validation enhancement for IEVS match received

---

Script Files/NOTES/NOTES - VERIFICATIONS NEEDED.vbs

Fixed the issue where it would case note "Sent form to AREP" if verif A was checked. Issue #1415

Update NOTES - VERIFICATIONS NEEDED.vbs

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

No file extension for MA EPD no initial premium made. Also removed old dates from the dialog boxes.
BLIP: bug fix to enable the script file to be accessed by users deployed, and updated "NEW" labels for new scripts from 10/15 - 11/15.

 file extension not included, bug fix in BETA

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

No file extension for MA EPD no initial premium made. Also removed old dates from the dialog boxes.
BLIP: bug fix to enable the script file to be accessed by users deployed, and updated "NEW" labels for new scripts from 10/15 - 11/15."

 file extension not included, bug fix in RELEASE

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

No file extension for MA EPD no initial premium made. Also removed old dates from the dialog boxes.
BLIP: bug fix to enable the script file to be accessed by users deployed, and updated "NEW" labels for new scripts from 10/15 - 11/15."

file extension not included, bug fix in MASTER

---

Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs
Script Files/DAIL/DAIL - NEW HIRE.vbs

#1364 
BLIP: Tikl will now include job name for ease of processing TIKL for ACTIONS new jobs, DAIL new hire, DAIL CS new job

Adding JOBs names to new hire tikls

---

README.md

updated title and references to SIR, resolves #1408

---

Script Files/NOTES/NOTES - MTAF.vbs

This is an MTAF (MFIP Transition Application Form) case note script.
It's meant to be used once the MTAF interview has been completed.

Resolves #81

---

Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs

added specific wording to notice for probate contact information. Also adds in a line in case note re: probate notice.
BLIP: Hennepin County only enhancement. Worker comments with county probate contact information if the program selected is Health Care, and the date of death option is selected.

Dod wcom hennepin

---

Script Files/MEMOS/MEMOS - APPOINTMENT LETTER.vbs

adding more locations to Ramsey County option, resolving issues #1266

Update MEMOS - APPOINTMENT LETTER.vbs

---

Script Files/NOTES/NOTES - MTAF.vbs

was interview completed, now "NOTES - MTAF.vbs"

changed FILE name

---

FUNCLIB CALL.vbs

Resolved #1419

---

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs

minor change/tweak to the funclib, resolving issue #1420

Update ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs

---

Script Files/DAIL/DAIL - ABAWD FSET EXEMPTION CHECK.vbs
Script Files/DAIL/DAIL - AFFILIATED CASE LOOKUP.vbs
Script Files/DAIL/DAIL - BNDX SCRUBBER.vbs
Script Files/DAIL/DAIL - CITIZENSHIP VERIFIED.vbs
Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs
Script Files/DAIL/DAIL - CSES PROCESSING.vbs
Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs
Script Files/DAIL/DAIL - DISA MESSAGE.vbs
Script Files/DAIL/DAIL - FMED DEDUCTION.vbs
Script Files/DAIL/DAIL - LTC - REMEDIAL CARE.vbs
Script Files/DAIL/DAIL - NEW HIRE.vbs
Script Files/DAIL/DAIL - SDX INFO HAS BEEN STORED.vbs
Script Files/DAIL/DAIL - STUDENT INCOME.vbs
Script Files/DAIL/DAIL - TPQY RESPONSE.vbs

Update FuncLib in DAIL scripts - Issue #1422

---

Script Files/NOTES/NOTES - LOBBY NO SHOW.vbs

Switched location of the OK and CANCEL buttons

Update NOTES - LOBBY NO SHOW.vbs

---

Script Files/ACTIONS/ACTIONS - ABAWD SCREENING TOOL.vbs
Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs
Script Files/ACTIONS/ACTIONS - CHECK EDRS.vbs
Script Files/ACTIONS/ACTIONS - COPY PANELS TO WORD.vbs
Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs
Script Files/ACTIONS/ACTIONS - FSET SANCTION.vbs
Script Files/ACTIONS/ACTIONS - LTC - SPOUSAL ALLOCATION FIATER.vbs
Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

tested and updated FUNC LIB block

ALL ACTIONS scripts

---

Script Files/NOTES/NOTES - GRH - HRF.vbs

BLIP: Updated header to read for the month case is being processed in. (post pay only looks at actual income rather than 2 month retro income). 
Updated header to include program information from first dialog. 
Added custom autofil from editbox to grab DOC and faci info.
Added difficulty of care (DOC) and other facility information to edit box/case note. 
Added logic to make sure autofill from elig doesn't grab unapproved version.
Cleaned up some code with modern functions.

various quality of life enhancements #1376

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

updated E & T phone number for Henn. Co.

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Updated COLA 2016 button/critical bug fix issue #1463 RELEASE branch

---

Script Files/NOTES/NOTES - LTC - ASSET ASSESSMENT.vbs

BLIP "Bug fix which caused assets to be written in multiple times in the case note. Error due to MAXIS panel update."
Also started cleaning the script up for an update.

Resolves #1467 in MASTER branch

---

Script Files/NOTES/NOTES - LTC - ASSET ASSESSMENT.vbs

BLIP "Bug fix which caused assets to be written in multiple times in the case note. Error due to MAXIS panel update."
Also started cleaning the script up for an update.

Resolves #1467 in RELEASE branch

---

Script Files/NOTES/NOTES - LTC - ASSET ASSESSMENT.vbs

BLIP "Bug fix which caused assets to be written in multiple times in the case note. Error due to MAXIS panel update."
Also started cleaning the script up for an update.

Resolves #1467 in BETA branch

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

This has been directly entered into the Appointment Letter at the DHS level for months.

Resolved #1407: agency address handling completely removed

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Resolves #1477  Tested and working.

BUGFIX NOTES - MFIP SANCTION DWP DISQUALIFICATION

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Update NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Bugfix NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

---

Script Files/BULK/BULK - BULK TIKLER.vbs

BLIP: out dated cancel confirmation was causing script error. Updated with modern function.

Fixing cancel_confirmation bug #1484

---

Script Files/MEMOS/MEMOS - DUPLICATE ASSISTANCE WCOM.vbs

Script to add WCOM to a SNAP or MFIP notice to alert clients to SNAP reduction due to Duplicate Assistance.

Added ability to WCOM MFIP Notice for Issue #1263

---

Script Files/NOTES/NOTES - APPLICATION RECEIVED.vbs

Needed to identify a footer month when date of application is entered manually

Fix so that it works when not in PND2 - Issue #1491

---

Script Files/MEMOS/MEMOS - APPOINTMENT LETTER.vbs

Resolves #1482.
Blip: Fixes a bug that was causing the script to get stuck on the self screen when run on a PND1 case in a month other than the APPL month.

Bugfix MEMOS - APPOINTMENT LETTER

---

Script Files/MEMOS/MEMOS - NOMI.vbs

Enhancements to the script include: a droplist of times for the missed appointment time, specific office information for Hennepin County users, and specific dialogs for Hennepin County with office information.

Hennepin co nomi enhancements

---

Script Files/MEMOS/MEMOS - MAIN MENU.vbs

Hennepin County will now be able to use the NOMI. 
In association with pull request #1498

Removed NOMI blocking for Hennepin County

---

README.md

Removed BETA information as this is now out dated.

Removed BETA information

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

Update ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

Leaves the dates fully intact in the array, (got rid of replace function) and grabs footer_month and footer_year using datepart.

This actually fixes the footer month problem.

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

Moved the 2nd dialog into the loop so it is recreated each time with the new set of properties, fixed some variable issues with UNEA.
It should be at least useable to test other panels on monday.

These updates make it testable

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

Removed some unnecessary lines
Added trims in a few places
Updated the syntax in the UNEA area in the OR logic to actually work
Assigned variables to class properties

Code cleanup - trims, syntax & class

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

navigate and pull info in all hh members. Also realigned a little because too much to the right

Adding in reading JOBS and BUSI information

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

BLIP: Enhancement to the E & T referral letter that will make the manual
referral if SNAP banked months are being used (this is a check box
options that users will select.

added manual referral when banked months are used: Resolves #1500 

---

Script Files/BULK/BULK - MAIN MENU.vbs

Cleans up the "new for" from the scripts description for scripts that are no longer considered "new". Issue #1375.

Update BULK - MAIN MENU.vbs

---

Script Files/NAV/OTHER NAV/NAV - OTHER NAV MAIN MENU.vbs

Cleans up "new" from a script description that is no longer considered "new". Issue #1375.

Update NAV - OTHER NAV MAIN MENU.vbs

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

Adds a button for the HOUSING GRANT FIATER and cleans up the "new for" info on scripts that are no longer considered new. Issue #1375.

Update ACTIONS - MAIN MENU.vbs

---

Script Files/BULK/BULK - ADDRESS REPORT.vbs
Script Files/BULK/BULK - CHECK SNAP FOR GA RCA.vbs
Script Files/BULK/BULK - COLA AUTO APPROVED DAIL NOTER.vbs
Script Files/BULK/BULK - FIND MAEPD MEDI CEI.vbs
Script Files/BULK/BULK - FIND PANEL UPDATE DATE.vbs
Script Files/BULK/BULK - INAC SCRUBBER.vbs
Script Files/BULK/BULK - LTC-GRH LIST GENERATOR.vbs
Script Files/BULK/BULK - MISC NON-MAGI HC DEDUCTIONS.vbs
Script Files/BULK/BULK - PDED LIST GEN.vbs
Script Files/BULK/BULK - REPT-ACTV LIST.vbs
Script Files/BULK/BULK - REPT-EOMC LIST.vbs
Script Files/BULK/BULK - REPT-INAC LIST.vbs
Script Files/BULK/BULK - REPT-MFCM LIST.vbs
Script Files/BULK/BULK - REPT-PND1 LIST.vbs
Script Files/BULK/BULK - REPT-PND2 LIST.vbs
Script Files/BULK/BULK - REPT-REVS LIST.vbs
Script Files/BULK/BULK - REPT-REVW LIST.vbs
Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs
Script Files/BULK/BULK - SWKR LIST GENERATOR.vbs

Resolves #1434. I did find a bug or two I fixed. There was a major one in the REPT REVS due to footer month being used in the navigate to screen function and it never being cleared after reading the CM+2 otherwise it was minor things. Tested each script at least one solo and with multiple people.

standardizing BULK to be 7 digit worker number input #1434

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

If current month + 1 is the initial date then exits do, otherwise it loops indefinately

added exit do to function resolves #1566

---

Script Files/DAIL/DAIL - CITIZENSHIP VERIFIED.vbs

BLIP: Script will now present user with a household member dialog allowing them to select unit members who have had their citizenship verified via DAIL and it will update MEMI with an OT verif and case note this action.

scriped edits memi, HH member dialog add #1250

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

BLIP: Added inhibiting feature for the following counties as they are
exempt from ABAWD work requirements: Aitkin, Clearwater, Hubbard,
Kanabec, Koochiching, and Lake of the Woods.

E and t exempt counties RESOLVES #1567

---

Script Files/BULK/BULK - REPT-PND2 LIST.vbs

BLIP: Added functionality to check interview status off of PROG. It will make a new column with a Y or N if the client has been interviewed for SNAP. 
Functionality for the checking what the results of the expedited screening is included as well but commented out due to concerns over validity of data. Both have been tested and do work. However more than half of the screenings were shown to have the opposite expedited status in small scale double checking.
Note to VKC: remove commented out functionality in order to pull script

Adding functionality to read interview

---

Script Files/NOTES/NOTES - HRF.vbs

BLIP: adding GA checkbox to case note GA HRFS, Adding checkbox to check ELIG/GA

Adding GA and fixing checkboxes #1574

---

Script Files/DAIL/DAIL - SEND NOMI.vbs

DAIL scrubber to be used with DAIL's created by the REVS scrubber.

Dail send nomi Resolves issue #711

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

fixes proration in initial month

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

BLIP: Adding check to make sure the script can access ELIG/DWP before proceeding to read eligibility results.
Resolves #1593

Update Approved Progs for DWP/MFIP transition

---

Script Files/ACTIONS/ACTIONS - MA-EPD EI FIAT.vbs
Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs
Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Script Files/ACTIONS/ACTIONS - SEND SVES.vbs
Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs
Script Files/ACTIONS/ACTIONS - UPDATE WORKER SIGNATURE.vbs

For some damn reason, 1/2 of the ACTIONS scripts did not save. 
BLIP: "Updated FuncLib block in the ACTION scripts."

resolves issue #1590, pulled into master branch

---

Script Files/NOTES/NOTES - COUNTY BURIAL APPLICATION.vbs

Blip: updated the tab order for sequential field navigation.

reordered the tab order in the dialog: resolves issue #1606

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

removed DCEX, and corrected some spelling errors.

added FMED and COEX expenses

---

Script Files/MEMOS/MEMOS - APPOINTMENT LETTER.vbs

This is old and was removed, scriptwriters are running into problems because it is looking for an old array.

Deleted old county_address_line determination, resolves #1618

---

Script Files/MEMOS/MEMOS - MNSURE MEMO.vbs

Added counter for Spec/Memo Else

Update MEMOS - MNSURE MEMO.vbs

---

Script Files/ACTIONS/ACTIONS - CHECK EDRS.vbs

Fix actions - check edrs

---

Script Files/NOTES/NOTES - MEDICAL OPINION FORM RECEIVED.vbs

Commenting out diagnosis field until we get response from PI. See issue #1589

Commenting out Diagnosis field

---

Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs

BLIP: Updating comments to resolve an Invalid Character error message.
Resolves #1629

Update ACTIONS - BILS UPDATER.vbs

---

Script Files/NOTES/CHANGE REPORTED.vbs
Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

Issue #1399 puts HHLD Comp change and Baby Born under one tab. Set 1 in Project Bowie.

Create NOTES - CHANGE REPORTED.vbs

---

Script Files/NOTES/NOTES - EXPLANATION OF INCOME BUDGETED.vbs

Created EXPLANATION OF INCOME BUDGETED script. 
BLIP: new script that is a template for explaining how income was budgeted for a case.

Resolves #183

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

in association with issue #186

added EXPLANATION OF INCOME BUDGETED button

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Duplicate code was left in creating logic loops. Fix was tested offline, but I was getting the error you're supposed to get when testing offline.
resolves #1661

Critical bug fix NOTES MAIN MENU #1661

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Resolves #956 
New script!
Blip - Searches caseload(s) by selected parameters. Will then transfer a specified number of those cases to another worker. - End Blip

BULK CASE TRANSFER

---

Script Files/BULK/BULK - MAIN MENU.vbs

Adding BULK CASE TRANSFER Button

---

Script Files/MEMOS/MEMOS - CS DISREGARD WCOM.vbs
Script Files/MEMOS/MEMOS - MAIN MENU.vbs

BLIP: Adding manual script for CS Disregard WCOM.
Resolves #1277

Create MEMOS - CS DISREGARD WCOM.vbs

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

error handling added for cases that:
Have RBIC income
Are over the gross income limits for the program
Users are from exempt counties

Resolves #1674

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

Added PF3 into JOBS array. Updated names of variables for SHEL, and added OTHER shel costs sections.

Resolves issue #1678, resolves issue #1679

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

BLIP: Added error handling to check for valid HH members, to update the
WREG panel for the selected HH member and added additional verbiage
about SNAP banked months.

added member number error handling resolves #1676

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

added button to actions main menu for the addition of the ABAWD BANKED
MONTHS FIATer

added button for banked months FIATer resolves #1685

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

Blip - Case notes when programs have been approved, improved handling for multiple cash programs and documenting Banked Months used.

Approved Programs Rewrite

---

Script Files/NOTES/NOTES - INTERVIEW COMPLETED.vbs

Resolves #1604 
Blanks out the CAF date if the date is more than 60 days old.

Interview Completed - Old CAF error check

---

Script Files/MEMOS/MEMOS - ABAWD WITH CHILD IN HH WCOM.vbs
Script Files/MEMOS/MEMOS - MAIN MENU.vbs

resolves #1468 
BLIP: Script will add a WCOM as prescribed in POLI/TEMP 02.05.70.30 when there is an adult in the SNAP HH and a child under 18 in the SNAP HH. Can write multiple people's names is allowed/needed.
"(Client's name(s)) is(are) exempt from Able Bodied Adult Without Dependents(ABAWD) work requirements due to a child(ren) under the age of 18 in the SNAP unit."

Adding new WCOM script

---

Script Files/UTILITIES/UTILITIES - INFO.vbs

BLIP: Adding the worker's signature to the Info script along with the capacity for the worker to update their default worker signature directly from the utility.
Larger explanation: The dialog building has been moved to a custom function. This allows the script to continuously refresh the worker signature without exiting the script.
Resolves #1612

Update UTILITIES - INFO.vbs

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

BLIP: added manual run time to banked months script

Banked month fiat time savings, resolves #1744

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

Added stats info to REVS scrubber

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

I honestly can't tell you why the error occurred, but now it's working with this pull.

resolves #1746 critical bug

---

Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

Resolves #1748
BLIP: The script has been updated to correct a typo that is preventing it from running. Additionally, variable names have been corrected for case. (During testing, case sensitivity seemed to matter. When the case was made consistent across the variable names, the script ran through perfectly.)

Critical Big Fix for NOTES - CHANGE REPORTED.vbs

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

Fix - pending elig amount not noted

---

Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

BLIP: The script has been updated to correct a typo that is preventing it from running. Additionally, variable names have been corrected for case. (During testing, case sensitivity seemed to matter. When the case was made consistent across the variable names, the script ran through perfectly.)
Resolves #1748

resolving critical bug in Change Reported

---

Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs

BLIP: script will now warn users when trying to enter a future paystub date.
resolves #1761

Fixing future paystub bug

---

Script Files/UTILITIES/UTILITIES - TRAINING CASE CREATOR.vbs

Swapped IF HC_application clauses to what they were supposed to be.

correcting HCRE mistake

---

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

BLIP: Should resolve issues of trying to nav to case note via pf4/pf9

adding start_a_blank_case_note

---

Script Files/NOTES/NOTES - AREP FORM RECEIVED.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

BLIP: Script case notes information regarding what programs AREP can speak about, when form was signed, if an AREP's ID is on file, and it can TIKL for 12 months for when a HC AREP release expires.
Also fixed a few width issues with descriptions on main menu
Resolves #1708

Adding AREP script

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

Removing shelter form button

---

README.md

BLIP: The project README file was updated with current and helpful information for scriptwriters and non-scriptwriters alike.

Resolved #1778: README is updated

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

BLIP: Several enhancements to this script include: adding manual referral option for eligible students, updated verbiage about when a manual referral should be made,  updated manual run time, added automatic TIKL option to TIKL out for 30 day return of verification of E & T compliance, added info to case notes for manual referral/TIKL information (if applicable).

Resolves #1779, resolves #1781, resolves #1782  SNAP E & T student manual referral enhancement

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Fixing Bug that transfers too many cases

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

BLIP: This update corrects the coordinates the script is writing on ELIG/GA and corrects the multidimensional array position location for case noting GA and MSA issuance. Previously, it was case noting the position for SNAP/MFIP Food.
Resolves #1771.

Fixes to NOTES >> APPROVED PROGS

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Blip - 'Fixes an issue where the script would transfer more cases than was requested'

Limit number of cases transferred

---

Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

Removes Baby's SSN from the dialog bog and case notes on the Baby Born part of the script.

resolved #1768: Update NOTES - CHANGE REPORTED.vbs

---

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs

Blip: "Additional instruction added for using the script to include sending a verification request form for E & T contact, informative message that a 30 day TIKL is automatically made when a manual referral is made. 'Eligible student' manual referral option was changed to 'student'.

Resolved #1789: SNAP E & T student info update

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/ACTIONS/ACTIONS - TYMA TIKLER.vbs
Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs
Script Files/DAIL/DAIL - TYMA SCRUBBER.vbs

BLIP: Added ACTIONS TYMA TIKLER for TIKLING all at once or TIKLING the first message(if agency processes as you go) based on GLOBAL VARIABLE: TYMA_TIKL_ALL_AT_ONCE (TRUE/FALSE)
Added DAIL TYMA SCRUBBER for clearing TYMA TIKLS if agency processes as you go.
Enhanced DAIL SCRUBBER to accept these TIKLS
Added button for ACTIONS TYMA TIKLER. 
Resolves #1792 resolve #1754

Resolves #1792 #1754 Adding TYMA TIKLERs

---

Script Files/NOTES/NOTES - HC RENEWAL.vbs

Blip; added message box to remind worker to update MMIS

Resolves #1238; new pop up box

---

Script Files/NOTES/NOTES - MSQ.vbs

Blip: This is a case note script that updates the STAT/ACCI panel when an MSQ form is not returned.  It will case note the details.
Resolves ISSUE #1148
FINALLY :-)

Resolves #1148 Create NOTES - MSQ.vbs

---

Script Files/NOTES/NOTES - EMPLOYMENT PLAN OR STATUS UPDATE.vbs

Blip: Corrected a bug with employment plan noting that was incorrectly notifying users that they needed to complete the school information field to continue.

resolves #1752

---

Script Files/NOTES/NOTES - FOSTER CARE REVIEW.vbs
Script Files/NOTES/NOTES-FOSTER CARE REVIEW.VBS

This scripts case notes when a foster care review is received for Health Care

Resolves #1812 Create NOTES - FOSTER CARE REVIEW.vbs 

---

Script Files/NOTES/NOTES - OHP RECEIVED.VBS
Script Files/NOTES/NOTES - OHP RECEIVED.vbs

Blip; this script is form when an out of home placement form is received, it will create a case note.

Resolves #342 Create NOTES - OHP RECEIVED.vbs

---

Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER OR NAME LOOK UP
Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER OR NAME LOOK UP.vbs

Combines the Phone number look up script and the REPT search look up script. Also fixes a looping issue.

Resolves #1603

---

Script Files/NAV/OTHER NAV/NAV - OTHER NAV MAIN MENU.vbs

removes the "phone number look up" button and the "REPT search" button and replaces them with the "phone number OR name look up" button.

#1603: Update NAV - OTHER NAV MAIN MENU.vbs

---

Script Files/NOTES/NOTES - CAF.vbs

Put in checkbox to indicate client is willing to work with E&T. Also arranged group of checkboxes in dialog box to make room and put in alphabetical order.

Resolves #1805 Update CAF with checkbox

---

TYPE - NEW SCRIPT TEMPLATE.vbs

A "new script template" is now available for scriptwriters to use when building scripts. It contains most mandatory fields, a FuncLib block,
statistics info, a sample do...loop, and logic to go to a case note.

Resolved #1827: a "new script template" is available

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

Blip: A new button that links to the "Utilities Main Menu" was added to the "Actions Main Menu". The UTILITIES Main Menu now contains the Update Worker Signature script and others.

Resolved #1835: added UTILITIES button to ACTIONS main menu

---

Script Files/UTILITIES/UTILITIES - MAIN MENU.vbs
Script Files/UTILITIES/UTILITIES - UPDATE WORKER SIGNATURE.vbs

Blip: Update Worker Signature is now a Utilities script. It can be found on the Utilities Main Menu (which is also crosslisted in the Actions Main Menu, in the top-right corner).

Resolved #1612: Update Worker Signature has moved

---

Script Files/UTILITIES/UTILITIES - INFO.vbs

Apparently this code is causing issues loading. Getting a ubound error, and not sure why. I don't have time to test before this release.
Originally part of #1612.

Addresses #1839: reverts pull request #1715

---

Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER OR NAME LOOK UP.vbs

Fixes the issue where the phone number look feature wasn't working on some of the searches.

Resolves #1833 fixes the issue with the phone number look up

---

Script Files/NOTICES/NOTICES - MAIN MENU.vbs

BLIP: Adding Dynamic SNAP WCOM submenu. Guidance for how to add to menu also included

Resolves #1734 Adding SNAP WCOM submenu

---

Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER OR NAME LOOK UP.vbs

No blip necessary as this is a new script (and it's only about statistics handling).

Resolved #1825: added stats handling in REPT lookup

---

Script Files/NOTES/NOTES - CAF.vbs

Blip:  added space and period.

resolved #1853  Updated CAF

---

Script Files/NOTES/NOTES - EXPEDITED DETERMINATION.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

Blip "New Script that creates a detailed case note about how Expedited was determined on a case. Includes actual case income/expenses and dates to detail timeliness."

Resolved #1264 - New script - Expedited Determination

---

Script Files/UTILITIES/UTILITIES - TRAINING CASE CREATOR.vbs

BLIP Added time savings handling in a few ways:
1: counts the time it takes to appl 1 case
2: counts the time it takes to update PROG/REVW (if script is asked to)
2: counts the time it takes to updated each panel (if script is asked to)
3: counts the time it takes to make each program approval (if script is asked to)
4: multiples by the number of cases APPL'd

RESOLVES #53 & #1626 Adding stats timesavings handling to Krabappel

---

Script Files/BULK/BULK - TIKL FROM LIST.vbs

BLIP: Corrected time savings counted to correctly reflect time savings from script.

Resolves #1867 Adding correct stats handling BULK TIKL to list

---

Script Files/BULK/BULK - CASE NOTE FROM LIST.vbs

BLIP: Corrected time savings counted to correctly reflect time savings from script.

Resolves #1867 Adding correct stats handling BULK CN from list

---

Script Files/BULK/BULK - MEMO FROM LIST.vbs

BLIP: Corrected time savings counted to correctly reflect time savings from script.

Resolves #1867 Adding correct status handling BULK MEMO from list

---

Script Files/BULK/BULK - MAIN MENU.vbs

BLIP: corrected links in buttons for MEMO and TIKL from list. Correct text bug on ADDR and the group box.

Resolves #1880 Button fix/text cleanup

---

Script Files/BULK/BULK - CASE NOTE FROM LIST.vbs
Script Files/BULK/BULK - TIKL FROM LIST.vbs

BLIP: These scripts still contained some references to their parent MEMO from list script. Corrected these and made sure the excel portion was working properly.

RESOLVES #1882 BULK CASENOTE/TIKL cleanup

---

Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs

Previous pull did not correct this due to me failing to notice what I fixed by accident.  Pulled version was slightly different from tested version, namely a capital letter.  blip remains the same as before.

resolves #1872 bug with Notices - SNAP E&T

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

1: max_reviews_per_worker is getting ABS'd which causes type mismatch error: Made conditional based on if it's entered
2: the text for the maximum interviews is getting cut off: Fixed

small fixes

---

Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

Quick fix so it case notes the "Other Notes" field from the baby born dialog.

Resolves #1893 - Case notes Other notes

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Blip - 'Fixed an error around comparing TANF Months. Conforms the entry to X-Numbers so that all 7 digits are entered.'

Resolved #1904, Resolved #1905: Fixes to BULK Case Transfer

---

README.md

Blip: the release notes link in the readme has been updated.

Resolved #1866: updated release notes link in README.md

---

Script Files/DAIL/DAIL - SEND NOMI.vbs

BLIP: updated the office hours for Hennepin County's NorthWest regional office from 5:00 to 4:30.

Resolves #1926

---

Script Files/BULK/BULK - COLA AUTO APPROVED DAIL NOTER.vbs

BLIP: Script was missing message boxes. Corrected error, script runs smoothly now.

RESOLVES #1928 adding missing msgboxes

---

Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/NOTICES/NOTICES - MAIN MENU.vbs

BLIP: BULK and NOTICES are in the same menu style as NOTES (in master)
Tested all buttons on both scripts.

RESOLVES #1889 #1899 Updating BULK and NOTICES with new dynamic DLG style

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

Blip: Corrects a bug that created an error message when attempting to update the banked month access database for cases with less than 3 months or multiple banked month members.

Resolves #1943 Notes - Approved Progs bug w/ banked month db

---

Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/BULK/BULK - UPDATE EOMC LIST.vbs

BLIP: This script will check all cases on a saved REPT/EOMC excel file from a previous month and update the file with current status for each program.

Resolves #657 New Script - Update EOMC List

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Makes it so that when you select add a WCOM that the script actually is able to add the WCOM.

Resolves #1948

---

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs

BLIP: Verbiage added to final message box reminding worker to send case file.

RESOLVES #1956 Adding verbiage about sending case file

---

Script Files/ACTIONS/ACTIONS - HOUSING GRANT FIATER.vbs

BLIP: Enhancement to the script includes handling for multiple months (up to current month plus one), updated dialog box,  and updated the statistical information.

Resolved #1887, Housing grant multiple months

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

BLIP: expanded some acronyms so descriptions are a bit more clear.

Resolves #1972 Expanding Acronyns.

---

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs

BLIP: Maxis now handles the CS disregard notice properly. WCOM is no longer needed.

RESOLVES #1981 Removing CS disregard WCOM

---

Script Files/NOTES/NOTES - LEP - SPONSOR INCOME.vbs

BLIP: Updating the constants for the 2016 sponsor income limits. See: CM0019.06.

Resolves #1975 -- Updating income limits

---

Script Files/NOTES/NOTES - CAF.vbs
Script Files/NOTES/NOTES - CLIENT CONTACT.vbs

Added checkbox to indicate interpreter was used for CAF interview.

Resolved #1979 Used Interpreter- CAF

---

Script Files/NOTICES/NOTICES - MAIN MENU.vbs

BLIP: Removed CS disregard from main menu as this script has been retired.

Resolved #1980:Removed CS disregard from NOTICE MM

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

BLIP: Removed CS disregard from main menu as script has been retired.

Resolved #1978: Actions cs disregard removed from main menu

---

Script Files/NOTES/NOTES - COMBINED AR.vbs

Updated the dialog and the case note portion of the script to add the eDRS checkbox and case note that it was checked.

Resolved #1953: add check eDRS checkbox

---

Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

Added the check box to the dialog for baby born asking if the babys managed health care plan has been updated to match the mothers.

Resolved #1955: reminder to add baby born to mom MHC plan

---

Script Files/NOTES/NOTES - EXPLANATION OF INCOME BUDGETED.vbs

Blip - 'Enhanced script to separate Self Employment income from other earned income and provides message about self employment policy. New field added to call out information about Overtime Income explanation'

Resolved #1806, #1917 - Explanation of Income Budgeted more detail

---

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs

This should merge the commits from RELEASE back into master to avoid a merge conflict.

#1978: syncing RELEASE changes to avoid merge conflict

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

adds a new button to the notes main menu for the returned mail script.

Issue #1993 New returned mail case note script

---

Script Files/ACTIONS/ACTIONS - HOUSING GRANT FIATER.vbs

Tim also pulled a fix for this, but it does not have the correctly handling for when a case is confirmed at issuing $110 through the FIAT for a single month. Only if it is confirmed that that $110 is not issued (the ELSE statement then attempts to FIAT for multiple months.)

Resolved #2006 HG fiater for multiple months

---

Script Files/NOTES/NOTES - FOSTER CARE HCAPP.vbs

Tightened up the dialog box for better viewing on smaller screens, and
added information/instructional text.

Resolved #1939: Updated Dialog Box

---

Script Files/UTILITIES/UTILITIES - INFO.vbs

Updated my county and contact information.

Resolved #1940: Info Script

---

Script Files/ACTIONS/ACTIONS - ABAWD SCREENING TOOL.vbs
Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
Script Files/NOTES/NOTES - CHANGE REPORT FORM RECEIVED.vbs
Script Files/NOTES/NOTES - CHANGE REPORTED.vbs
Script Files/NOTES/NOTES - CLIENT CONTACT.vbs
Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs
Script Files/NOTES/NOTES - COMBINED AR.vbs
Script Files/NOTES/NOTES - CSR.vbs
Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs
Script Files/NOTES/NOTES - DOCUMENTS RECEIVED.vbs
Script Files/NOTES/NOTES - EMERGENCY.vbs
Script Files/NOTES/NOTES - EXPEDITED DETERMINATION.vbs
Script Files/NOTES/NOTES - HC RENEWAL.vbs
Script Files/NOTES/NOTES - HCAPP.vbs
Script Files/NOTES/NOTES - HRF.vbs
Script Files/NOTES/NOTES - INTERVIEW COMPLETED.vbs
Script Files/NOTES/NOTES - MFIP TO SNAP TRANSITION.vbs
Script Files/NOTES/NOTES - MTAF.vbs
Script Files/NOTES/NOTES - OVERPAYMENT.vbs
Script Files/NOTES/NOTES - VERIFICATIONS NEEDED.vbs
Script Files/NOTICES/NOTICES - APPOINTMENT LETTER.vbs

Blip - 'Updates to a number of prioritized scripts to enhance the passworded out handling that will make use easier for users running BlueZone version 6.'

Resolved #1977 - Adding Passworded Out Handling

---

Script Files/NOTICES/NOTICES - NOMI.vbs

Putting back the missing END IF for the x127 specific section.

Resolves #2032 bug in Notices - NOMI

---

Script Files/NAV/NAV - CASE-CURR.vbs

BLURB: updated internal stats collecting function, end users will see no change in performance

Addresses #2042 updating stats block

---

Script Files/BULK/BULK - CHECK SNAP FOR GA RCA.vbs

Blip: Script users are given the option to add the worker's supervisor to the script's output.

Addresses #2061 Option to add supervisor to GA/RCA check

---

Script Files/BULK/BULK - FIND PANEL UPDATE DATE.vbs

Blip: Gives users the option to add the worker's supervisor's name to the output of the report for easier distribution when running this report on other users' caseloads.

Address #2061 Adds option to add supervisor name to Find Panel Update Date

---

Script Files/NOTES/NOTES - DECEASED CLIENT SUMMARY.vbs

Script file for case noting details about deceased client.

Resolved #2054 new script created

---

Script Files/NOTES/NOTES - MAIN MENU.vbs
Script Files/NOTICES/NOTICES - MAIN MENU.vbs

No need for a blip as this already has a registered blip.

Resolved #2072: added two new scripts to main menu files

---

Script Files/NAV/OTHER NAV/NAV - PRISM SCREEN FINDER.vbs
Script Files/NAV/OTHER NAV/PRISM SCREEN FINDER.vbs

This new script is intended to assist financial workers in navigating to popular screens in PRISM.  To use, simply press the button for the screen you are looking to go to when open in PRISM.  At the screen, press F1 in the case number, or MCI number field to search for and select the participant whose information you would like to see.

Resolves #2074

---

Script Files/BULK/BULK - UPDATE EOMC LIST.vbs

pulling to release for critical, see master pull for blip

Resolves #2077 Bug with BULK - Update EOMC List

---

Script Files/ACTIONS/ACTIONS - SHELTER EXPENSE VERIF RECEIVED.vbs

BLIP: Logic surrounding room & board was incorrect, fixed IF statement and added section to actually case note room & board notes.

RESOLVES #2047 Reworking room&board logic

---

Script Files/NOTES/NOTES - RETURNED MAIL RECEIVED.vbs

I've updated the script to include the manual run time for stats gathering purposes.

Resolved #2088: adds manual run time to the returned mail script

---

Script Files/NOTES/NOTES - RETURNED MAIL RECEIVED.vbs

Variable names updated to be more descriptive.

Resolved #2091

---

Script Files/BULK/BULK - TARGETED SNAP REVIEW SELECTION.vbs

BLIP: This is a new script that will allow agencies to select SNAP cases for internal review based on specific criteria to help identify error-prone cases. Selects both PAR (ACTIVE) and CAPER (closed/denied) cases for review. The script collects cases off rept/actv and rept/inac and adds those cases meeting selection criteria to a spreadsheet. Once the lists have been built, it selects at random the specified number of each review type and adds them to a new sheet to be assigned for review.

Resolves #2093 New Script Targeted SNAP REVIEW

---

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs

BLIP: Script will now better prompt user for information regarding withdrawn programs. It will check Pnd2 and based on what worker has coded try to insure worker completes dialog properly based on the types of denials.

RESOLVES #1879 adding withdraw handling

---

Script Files/BULK/BULK - CHECK SNAP FOR GA RCA.vbs

BLIP: The script's output has been expanded to display the GA monthly grant and the GA issuance amount separately (should the client happen to have a GA overpayment).

Resolves #2104 -- Expanding Output

---

Script Files/NOTICES/NOTICES - APPOINTMENT LETTER.vbs

Added interview address for Carver County and for each of the MNPrairie locations (Dodge, Steele & Waseca Counties)

Resolves #2070: Update NOTICES - APPOINTMENT LETTER.vbs

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

Blip: Adds a reminder on the dialog that users should not share FTI information with other agencies by using this form.

Resolves #2103 PA Verif FTI verbiage

---

Script Files/UTILITIES/UTILITIES - TRAINING CASE CREATOR.vbs

Blip: a redundant function was removed, end-users should not notice any changes.

Resolved #2087: removed function behind-the-scenes

---

Script Files/NOTICES/NOTICES - NOMI.vbs
Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs

BLIP: updated Hennepin County's Northwest regional office hours to reflect daily hours of 8 - 430. Also moved the stats block to the top of the script behind the scenes.

Resolved #2108, NOMI Hennepin NW office update

---

Script Files/NOTES/NOTES - PROOF OF RELATIONSHIP.vbs

Blip - 'Enhanced to support detailing multiple relationships and verifications at once, also will now autofill information from MAXIS into the script.'

Resolves #1958 - Proof of Relationship multiple people

---

Script Files/NOTES/NOTES - LEP - SAVE.vbs

BLIP: Behind the scenes fixes to make the script run better and be more user friendly.
(I'm going to be away from the office starting tomorrow so I figured I'd throw the pull up so it wasn't delayed too long. No urgency on this pull, just quality of life fixes. )

RESOLVES #2127 Modernizing script

---

Script Files/BULK/BULK - MAIN MENU.vbs

BLIP: Internal fix to make script run without error.

RESOLVES #2156 Missing object delcaration

---

Script Files/NOTICES/NOTICES - ELIGIBILITY NOTIFIER.vbs
Script Files/NOTICES/NOTICES - MA INMATE APPLICATION WCOM.vbs
Script Files/NOTICES/NOTICES - MAIN MENU.vbs

Adding two new scripts and updating Main Menu
Eligibility Notifier
BLIP: this script will send a MEMO to the client to notify them of potential eligibility for MA, MSP, Mnsure, SNAP, or Cash programs. It also contains information regarding how to apply, and CAF1 importance.
MA Inmate Application WCOM
BLIP: adds a wcom to a MA approval notice to inform clients who have applied for MA while in the process of being release from a correctional facility of their MA start date. This start date is determined by trying to read the FACI panel for a release date.

RESOLVES #2148 & #2153

---

Script Files/DAIL/DAIL - ABAWD FSET EXEMPTION CHECK.vbs

BLIP: The script will display the results of the ABAWD/FSET Exemption Check.

Resolves #2163 -- Displaying msgbox with results

---

Script Files/DAIL/DAIL - SEND NOMI.vbs
Script Files/NOTES/NOTES - GOOD CAUSE RESULTS.vbs
Script Files/NOTICES/NOTICES - NOMI.vbs

BLIP: "Updated script to reflect Hennepin County's NW office opening at 8:00 a.m."

Resolved #2168, Hennepin Co NW office hours

---

Script Files/NOTICES/NOTICES - MAIN MENU.vbs

BLIP: corrected typo on script description

RESOLVES #2171 correcting typo

---

Script Files/BULK/BULK - FIND PANEL UPDATE DATE.vbs
Script Files/NOTES/NOTES - GOOD CAUSE RESULTS.vbs

BLIP: Added PACT, PARE, PBEN, STWK and WREG options to the script. Users can now search these MAXIS screens for updated dates based on time perimeters selected in the initial dialog."

Resolved # 2130, Added PACT, PARE, PBEN, STWK and WREG

---

Script Files/NOTES/NOTES - GOOD CAUSE RESULTS.vbs
Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs

BLIP: Added "other manual referral" option to the "manual referral needed" droplist. The "other manual referral notes" is a mandatory field if the 'manual referral' option is selected. This field will be notes added to the manual referral."

Resolved #2174, enhancement to add 'other manual referral' option

---

Script Files/ACTIONS/ACTIONS - LTC - ICF-DD DEDUCTION FIATER.vbs
Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
Script Files/NOTES/NOTES - GOOD CAUSE RESULTS.vbs

BLIP: New script will FIAT earned income disregards on STAT/WKEX for LTC clients in ICF-DD's that receive earned income. Deductions will be FIATed for a selected month through the active budget period.

Resolved #2057: LTC - ICF-DD earned income FIATer

---

Script Files/NOTES/NOTES - GOOD CAUSE RESULTS.vbs

corrected the lower case name to all caps for statistical tracking.

Resolved #2031 Corrected NOTES - GOOD CAUSE RESULTS name 

---

Script Files/NOTES/NOTES - FOSTER CARE HCAPP.vbs

BLIP: Updating the script to case note the actions taken.

Resolves #2182 -- Case noting actions taken

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs
Script Files/ACTIONS/ACTIONS - ABAWD SCREENING TOOL.vbs
Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs
Script Files/ACTIONS/ACTIONS - CHECK EDRS.vbs
Script Files/ACTIONS/ACTIONS - COPY PANELS TO WORD.vbs
Script Files/ACTIONS/ACTIONS - FSET SANCTION.vbs
Script Files/ACTIONS/ACTIONS - LTC - SPOUSAL ALLOCATION FIATER.vbs
Script Files/ACTIONS/ACTIONS - MA-EPD EI FIAT.vbs
Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs
Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Script Files/ACTIONS/ACTIONS - SEND SVES.vbs
Script Files/ACTIONS/ACTIONS - SHELTER EXPENSE VERIF RECEIVED.vbs
Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs
Script Files/ACTIONS/ACTIONS - TYMA TIKLER.vbs

all ACTION scripts have stats block at being of script

Addresses #1938 updates location of stats block to top of scripts 

---

BULK - BULK SCRIPT TEMPLATE.vbs

Blip: A template for scriptwriters to use as a starting point for developing custom bulk scripts.

Resolves #2167 Bulk Script Template

---

Script Files/BULK/BULK - RETURNED MAIL.vbs

Blip: the following functions were depreciated across all scripts:
* `ERRR_screen_check`
* `maxis_check_function`
* `navigate_to_screen`
* `write_editbox_in_case_note`
* `write_new_line_in_case_note`
* `write_new_line_in_SPEC_MEMO`
* `worker_county_code_determination`
* `write_TIKL_function`

Resolved #2195: all depreciated functions are updated

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

Removed duplicated code for developer mode. Added conditions within an ELSE...IF to perform functions specific to developer mode vs. production. Changed case_number to MAXIS_case_number, updated dialogs to have check_for_password handling, and updated the STATS counting to include counting cases that are ACTV on MFIP.

Cleaning up the REVS Scrubber, associated with issue #710

---

Script Files/NOTICES/NOTICES - MFIP ORIENTATION.vbs

Blip: Added a list of agency office addresses within the script to correct an issue with the address auto-fill in the dialog.

Resolves #2140 NOTICES - MFIP ORIENTATION Address list

---

Script Files/NOTICES/NOTICES - POSTPONED WREG VERIFS.vbs

BLIP: Script will now TILK for next cutoff date to close case. Since this script is designed for the postponed wreg verification workaround we are supposed to close the case in accordance with expedited processing. This means sometimes closing cases before a ten day period to turn in verifications (to meet cutoff requirements).

RESOLVES #2123 adding cutoff date calculating

---

Script Files/NOTICES/NOTICES - MA INMATE APPLICATION WCOM.vbs

BLIP: Script will now more accurately find the most recent release date from the FACI panel by comparing all the most recent end dates from every FACI panel.

RESOLVES #2219 Reworking finding release date

---

Script Files/BULK/BULK - UPDATE EOMC LIST.vbs

Blip: Fixes a bug that was causing the script to update the list with incorrect case statuses.

Resolves #2181 Bug with BULK - Update EOMC List

---

Script Files/BULK/BULK - FIND PANEL UPDATE DATE.vbs

This is the only panel in the script that is case-based. Removed person-based coding to improve speed.

Resolved #2222, Panel update date pact- removed person-based coding

---

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs

Blip: When sending a SPEC/MEMO with new worker information, the script will now check if notices are to be sent to an AREP or Social Worker, and send copies of the memo if needed.  It also case notes the action.  A minor bug was also corrected that prevented sending the memo when transferring a privileged case.

Resolves #2192 ACTIONS - CASE TRANSFER memos to arep / swkr

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs
Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs
Script Files/BULK/BULK - ADDRESS REPORT.vbs
Script Files/BULK/BULK - HOUSING GRANT EXEMPTION FINDER.vbs
Script Files/BULK/BULK - REPT-MFCM LIST.vbs
Script Files/BULK/BULK - REPT-REVS LIST.vbs
Script Files/BULK/BULK - REPT-REVW LIST.vbs
Script Files/DAIL/DAIL - SEND NOMI.vbs
Script Files/NAV/OTHER NAV/NAV - PHONE NUMBER OR NAME LOOK UP.vbs
Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs
Script Files/NOTES/NOTES - SUBMIT CASE FOR SNAP REVIEW.vbs
Script Files/NOTICES/NOTICES - GRH OP CL LEFT FACI.vbs
Script Files/NOTICES/NOTICES - NOMI.vbs
Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs

Blip was added as part of #2195, #1938, and several FuncLib updates.

Resolved #2223: get_county_code has been included

---

Script Files/BULK/BULK - FIND MAEPD MEDI CEI.vbs

BLIP: added comments for internal users and code review.

RESOLVES #2234 Adding comments

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

Several updates include: moved stats block to top of script, cleaned up multiple dates per new global constants added to the FuncLib, added flair (vbExclamation) to VbOkCanel, added handling for cases that do not have HCRE completed for all HH members (other wise cases go into edit mode, and required a user to manually PF10 to continue), removed outdated functions and replaced with current custom functions, fixed date in MEMO to display 2-digit (which resolves the "//" issue in the MEMO.

Added updated interview required determination

---

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs

BLIP: The script now takes the user name (for in county transfers) and checks REPT/USER to find the new worker's contact information and enters it into the MEMO.

RESOLVES #2242 Reworking in county transfer memo

---

Script Files/BULK/BULK - BANKED MONTHS REPORT.vbs

This is a fix to a new script for release on Monday

Resolves #2247 - Banked Months Report counting ABAWD months incorrectly

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

BLIP: You can now list specific items and/or services as being applied to the BFE. This will then be calculated and displayed in detail on the case note. Also added alternative container to Burial space/items list. Added luncheon, and medical exam fee to cash advance items.

RESOLVES #2245 Adding option to count BFE accurately.

---

Script Files/BULK/BULK - REPT-PND1 LIST.vbs

REPT PND1 List has_content_check has been updated to look for an entire case number rather than one digit, eliminating missed cases on the bulk list.

Resolved #2258 (partial): Fixed content check/PND1

---

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

BLIP: Script will now correctly case note MAGI reinstate dates.

RESOLVES #2265 moving MAGI read to right place

---

Script Files/BULK/BULK - TARGETED SNAP REVIEW SELECTION.vbs

Blip:  The script will now only select active cases that have had a SNAP approval in current month minus one, to align with review month for CAPER cases.

Resolves #2262 Targeted SNAP Review review date enhancement

---

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs

#1714 - variable update - MAXIS_case_number

---

Script Files/NOTES/NOTES - LTC - ASSET ASSESSMENT.vbs

BLIP "Function added to the script has a typo causing a user error. Corrected the spelling of the function."

Resolved #2285

---

Script Files/NOTES/NOTES - LTC - ASSET ASSESSMENT.vbs

BLIP "Function added to the script has a typo causing a user error. Corrected the spelling of the function."

Resolved issue #2285

---

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs
Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/ACTIONS/ACTIONS - SEND SVES.vbs
Script Files/NOTES/NOTES - AREP FORM RECEIVED.vbs
Script Files/NOTES/NOTES - BABY BORN.vbs
Script Files/NOTES/NOTES - DECEASED CLIENT SUMMARY.vbs
Script Files/NOTES/NOTES - HH COMP CHANGE.vbs
Script Files/NOTES/NOTES - INCARCERATION.vbs
Script Files/NOTES/NOTES - LTC - 1503.vbs
Script Files/NOTES/NOTES - LTC - 5181.vbs
Script Files/NOTES/NOTES - PREGNANCY REPORTED.vbs
Script Files/NOTES/NOTES - VERIFICATIONS NEEDED.vbs

Blip - 'Changing the standard for how dialogs are handled for scripts selected for the Change Reported Workflow'

Resolves #2110 - Renaming the Bowie Dialogs

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Blip - 'Fixes the script so that the cases will transfer without a MAXIS
error.'

Resolves #2246 - Bulk Case Transfer Bug

---

Script Files/BULK/BULK - MAGI NON MAGI REPORT.vbs
Script Files/BULK/BULK - MAIN MENU.vbs

BLIP: This new script checks the inputted MAXIS caseloads for MAGI/Non-MAGI Health Care cases. Users have the option of adding the caseload's supervisor to the output. Additionally, users have the option of adding the status of CASH and SNAP on the MAXIS case.

Resolves #2112 -- Creating MAGI/Non-MAGI Report

---

Script Files/BULK/BULK - IEVS REPORT.vbs
Script Files/BULK/BULK - MAIN MENU.vbs

Blip - 'This is an new script that will create a report of information found on IEVC, including statistics and overdue instances. This script can also be run for the entire agency.'

Resolves #2281 - New IEVC Report

---

Script Files/NOTES/NOTES - LTC - COLA SUMMARY.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

BLIP: Script can now enter the month the worker choose rather than being limited to one approval month per COLA cycle.

RESOLVES #2276 updating LTC COLA to allow for more than 01/16 approvals

---

Script Files/BULK/BULK - REPT-ARST LIST.vbs

Blip - 'Enhancement to the script that will include the total case counts for workers to the report, since these are different from the program based counts.'

Resolves #2131 - Adding Case totals to REPT ARST

---

Script Files/BULK/BULK - DAIL REPORT.vbs

Blip - 'Fixes a bug so the script does not get stuck if a worker has no DAILs listed'

Resolves #2309 - DAIL Report error

---

Script Files/NAV/OTHER NAV/NAV - PRISM SCREEN FINDER.vbs

Resolves #2217 - Updating statistics code so that agencies that collect usage statistics calculate accurate information.

Resolves #2217

---

COMPLETE LIST OF SCRIPTS.vbs
Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/BULK/BULK - REPT-MAMS LIST.vbs

BLIP: New BULK script pulls a list of cases in REPT/MAMS into an Excel spreadsheet

Resolved #2318 BULK - REPT MAMS LIST

---

Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs

BLIP: Sanction period will now contact days as opposed to only month/year giving a better indicator of the actual period of the sanction.

RESOLVES #2264 Expanding sanction dates

---

Script Files/NOTICES/NOTICES - METHOD B WCOM.vbs

BLIP: Removed duplicate wording and minor spelling error.

Resolved #2230: Method B WCOM clean up

---

Script Files/UTILITIES/UTILITIES - INFO.vbs

BLIP - 'adding new script writer from Ramsey county to the info'

RESOLVES #2284 - ADDING KENNY TO INFO

---

Script Files/BULK/BULK - TARGETED SNAP REVIEW SELECTION.vbs

Blip: Corrects an error that was preventing the script from selecting cases for the audit spreadsheet in certain circumstances.

Resolves #2325 Targeted SNAP review BUG

---

Script Files/ACTIONS/ACTIONS - CHECK EDRS.vbs

BLIP: Script should now not cause users to be passworded out by running the script.

RESOLVES #2339 adding additional check_for_maxis functions

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

BLIP: added a new function for developer mode to allow it to be run on CM+1 before the 16th like it used to.

ADDRESSES #710 Adding functionality for testing cases before the 16th. 

---

README.md

Blip: the README was updated to include guidelines about when scripts should be removed from the project.

Resolved #2344: added bit about when to remove a script from the project

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

I will also pull the final version once I removed the Outlook information.
Updates include: 
*updated FUNC LIB Block
*removed duplicate code for running script prior to the 16th and developer mode
* Updated several date variables to global constant dates in FuncLib
* General clean up of code 
Tested and working!

Updated REVS scrubber with Outlook piece still intact

---

Script Files/UTILITIES/UTILITIES - COPY CASE NOTE ELSEWHERE.vbs
Script Files/UTILITIES/UTILITIES - COPY CASE NOTE TO.vbs
Script Files/UTILITIES/UTILITIES - MAIN MENU.vbs

BLIP: this script will allow users to copy a case note into claim notes or into a MEMO. NOTE: MEMO has a smaller space for writing so not all case notes will fit.

RESOLVES #2263 New script UTILITIES - COPY CASE/NOTE ELSEWHERE

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

Removed Outlook functionality. 
Tested again, and working like a charm! 
Will submit a pull request in the master branch to add this to the BULK main menu and the Complete list of scripts.

Resolved #710: Final version of Project Mic drop

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

Missed a period. Added the period.

Resolved #2354: Missing punctuation in MEMO of REVS SCRUBBER

---

Script Files/NOTICES/NOTICES - NOMI.vbs

BLIP: added NOMI_selection as a mandatory field for Hennepin County users only.

Resolved #2359: mandatory field added for x127 users

---

Script Files/BULK/BULK - MAIN MENU.vbs

Added REVS Scrubber to the BULK - MAIN MENU

Resolved #2367: Added REVS Scrubber to the BULK - MAIN MENU

---

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs

BLIP: End message verbiage will correctly state if a TIKL was created.

RESOLVES #2374 changing end message verbiage

---

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs

BLIP: Script now has better functionality regarding calculation for specific assets. 
A dynamic calculator that displays current totals for counted assets and assets applied to the BFE. When the user hits a button the calculator will refresh, it will also make sure the user doesn't enter more than $1500 into the BFE and appropriately relabel the last item to push the BFE over $1500 to BFE/counted (it will also let the user know of this change and inform them to review it). This is more in line with examples found in LTC training case notes.
A preview messagebox after the user enters all of the information. This box will display the totals, what items were selected, what their items values are, and what the status of the item is (counted excluded etc). User can then go back to change …

RESOLVES #2343 Overhaul with calculator

---

Script Files/NOTES/NOTES - CLIENT CONTACT.vbs

BLIP - 'ADDED FIELD FOR MNSURE/IC NUMBER FIELD TO DIALOG. WILL CASE NOTE IT ALSO'

RESOLVES #2379

---

Script Files/ACTIONS/ACTIONS - TYMA TIKLER.vbs

Blip - 'Fixes a typo in the case note that lists 1st Quarter twice'

Resolves # 2384 - TYMA TIKL Typo

---

Script Files/UTILITIES/UTILITIES - BANKED MONTH DATABASE UPDATER.vbs
Script Files/UTILITIES/UTILITIES - COPY CASE NOTE ELSEWHERE.vbs
Script Files/UTILITIES/UTILITIES - COPY PANELS TO WORD.vbs
Script Files/UTILITIES/UTILITIES - INFO.vbs
Script Files/UTILITIES/UTILITIES - MAIN MENU.vbs
Script Files/UTILITIES/UTILITIES - PHONE NUMBER OR NAME LOOK UP.vbs
Script Files/UTILITIES/UTILITIES - POLI TEMP LIST.vbs
Script Files/UTILITIES/UTILITIES - PRISM SCREEN FINDER.vbs
Script Files/UTILITIES/UTILITIES - TRAINING CASE CREATOR.vbs

Blip for #2380: several utilities scripts had new function blocks installed. End users should not notice any change in the scripts.
Regarding #2159: I moved the dialogs to new locations, to help #2159 work better. Let's hope it works.

Resolves #2380 and addresses #2159

---

Script Files/BULK/BULK - INAC SCRUBBER.vbs

BLIP: Script will now correctly loop through case number rather than getting stuck on last case number case/noted on.

RESOLVES #2389 correcting variable issue

---

Script Files/BULK/BULK - INAC SCRUBBER.vbs

BLIP: Script will now correctly loop through case number rather than getting stuck on last case number case/noted on.

RESOLVES #2389 correcting variable issue(RELEASE)

---

Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs

BLIP: generalized HC reinstate information on dialog to refer workers to check with policy.

RESOLVES #2400 generalizing HC rein information

---

Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs
Script Files/DAIL/DAIL - POSTPONED XFS VERIFICATIONS.vbs

Blip - 'New DAIL Scrubber script that will case note about SNAP Closing from this DAIL Message - 'CASE AUTO-CLOSED FOR FAILURE TO PROVIDE POSTPONED VERIFICATI'. This note is specific to Expedited SNAP closing for no receipt of delayed verifications.'

Resolves #2046 - DAIL Scrubber for XFS AutoClosing

---

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs

Blip - 'The script will now check PBEN for any Unemployment Benefits pending as a possible ABAWD/FSET exemption.'

Resolves #2372 - ABAWD Exemption Check - UI Pending

---

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs

Finds the information and then adds the specific case note information for Self Declaration of Over Income Policy on SNAP applications.

Resolved #2388: Self Declaration of Over Income Policy.

---

Script Files/ACTIONS/ACTIONS - PA VERIF REQUEST.vbs

BLIP: Updated script to provide full program names in addition to the program acronyms. Also added a program key for recipients to reference when the user selects to include a screen print of the issues. Updated the logic for checking for a password prompt, mandatory fields and redesigned the main dialog.

Resolved #2416: Added program names/key to ACTIONS - PA VERIF REQUEST

---

Script Files/BULK/BULK - CASE NOTE FROM LIST.vbs

Blip - 'Enhancement to the script so that it pulls wording from an existing case note if the script is started from the case note.'

Resolves #2395 - Bulk Case note from list using existing case note

---

Script Files/NOTICES/NOTICES - POSTPONED WREG VERIFS.vbs

Blip - 'Fixes an error in determining dates used in the script.'

Resolves #2393 - WREG Verifs WCOM Date Bug

---

Script Files/NOTICES/NOTICES - APPOINTMENT LETTER.vbs

Blip: added Nicollet County intake addresses to the Appointment Letter
script.

Resolved #2425: new addresses added to Appointment Letter

---

Script Files/UTILITIES/UTILITIES - INFO.vbs

BLIP: Roles/contacts updated for Veronica and Charles

RESOLVES #2444 Updating roles for CDP and VKC

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs

BLIP: Updated the script to account for cases that have the initial month coded as an "X" on the ABAWD tracking record.

Resolved #2454: Banked months FIATer ABAWD tracking record confirmation.

---

Script Files/NOTES/NOTES - OVERPAYMENT.vbs

BLIP: Added a new dropdown to select if the claim can be collected (options are YES, NO, or N/A), and added a field for workers to enter calculations and explanations as to why or why not the claim is collectible.

RESOLVES #2452 updating for new cash claims process

---

Script Files/NOTES/NOTES - CSR.vbs

Blip: Added GRH checkbox for users to select CSR, added ELIG/GRH navigation button to dialogs. Also  updated date variables to global constants and footer month functions on the back end.

Resolved #2453, Added GRH to NOTES - CSR

---

Script Files/NOTES/NOTES - CHANGE REPORTED.vbs

BLIP - 'Added gender dropdown list and mother/member number drop down list'

RESOLVES #2450 and #2451 - add gender/mother field

---

Script Files/NOTES/NOTES - EXPEDITED SCREENING.vbs

BLIP: Script is now prepared for changes to shelter deduction standards effective 10/1/16

RESOLVES #2464 Updated constants

---

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs

#1714 - CSES Scrubber - case noting and good things.

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

BLIP: removed outdated 'new' script indicators from the NOTES - MAIN MENU

Resolved #2474, removed outdated 'new' script indicators

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Script Files/ACTIONS/ACTIONS - LTC - SPOUSAL ALLOCATION FIATER.vbs
Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Script Files/DAIL/DAIL - NEW HIRE NDNH.vbs
Script Files/DAIL/DAIL - NEW HIRE.vbs

BLIP: Scripts were updated to prepare for the change to the jobs panel including moving fields. This is only for the critical issue of the scripts pointing at the wrong place. New types for SCHL/JOBS/UNEA to be added once we get hands on the panels.

RESOLVES #2485 Fixed scripts which point to changing fields

---

Script Files/BULK/BULK - CASE TRANSFER.vbs

Blip - 'A limiter has been added so that the script run time will be reduced if only a small number of cases need to be found.'

Resolves #2492 - Bulk Case Transfer

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Script Files/ACTIONS/ACTIONS - LTC - SPOUSAL ALLOCATION FIATER.vbs
Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs

Adding new income types for actions scripts. New income types include:
JOBS: T Training Program P Service Program R Rehab Program
UNEA: 47 Counted Tribal Income 48 Trust Income 49 Non-Recurring Income > $60 per Quarter

RESOLVES #2496 Fix to actions panels for jobs change

---

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs

The script is now case noting correctly after reviewing UNEA panels.  Added logic to check if it made it to note, and fixed typos in case note function call.

Resolves #2500 New CSES Scrubber not able to note

---

Script Files/NOTES/NOTES - COMBINED AR.vbs

The script has been updated to show what programs are being recertified in the case note.

Resolved #2512 Adding programs to CAR note

---

Script Files/NOTES/NOTES - FOSTER CARE HCAPP.vbs

Added fields for HHcomp and assets

Resolved #2509 Added Text boxes

---

Script Files/NOTES - PARIS MATCH.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

This is a script that case notes a PARIS match action.  This can be used to case note if the match was resolved or if a notice was sent to the client.  Worker also indicates the month of the match, Household member, State where the match occurred, the matched program, and the resolution code used.

Resolved #2412 NEW SCRIPT PARIS Match case note

---

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

BLIP: Updated HC reinstatement and new intake date to reflect the 4 month reinstatement period for all HC programs (not MAGI only).

Resolved #2503, Revw mont closure

---

Script Files/NOTES/NOTES - HCAPP.vbs

Added a Combo-box to choose the type of HCAPP that was received.

Resolved #2495 HCAPP script

---

Script Files/NOTES/ NOTES - PARIS MATCH.vbs

This is a script that case notes a PARIS match action. This can be used to case note if the match was resolved or if a notice was sent to the client. Worker also indicates the month of the match, Household member, State where the match occurred, the matched program, and the resolution code used.

Resolved #2412 Create- Notes- Paris Match

---

Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs
Script Files/DAIL/DAIL - ES REFERRAL MISSING.vbs

Blip - New functionality for DAIL Scrubber that will process PEPR Message - ES Referral Date Needed. Script will find the date on INFC/WORK and will update EMPS and Case Note the action.'

Resolves #2528 - ES Referral Needed DAIL

---

Script Files/DAIL/DAIL - FIN ORIENT MISSING.vbs

Blip - 'New functionality for the DAIL Scrubber for PEPR Messages about Financial Orientation Date Missing. Script will find a couple of dates that may be appropriate and allow user to chose or select their own date, then it will update EMPS and case note the action.'

Resolves #2529 - New DAIL Scrubber - Financial Orientation Date

---

Script Files/NOTES/NOTES - EVF RECEIVED.vbs

Dialog box updated to reflect current standardization. The size of the edit boxes and order of information matches the case note. 
Checkbox was added for the worker to Tikl for 10 days if additional information was requested. It is auto-checked and can be removed if no additional information is needed (e.g. EVF was completed by employer)
Header updated to indicate whether the EVF was Signed by client, completed by employer, or both. Header will change depending on what the worker selects for the EVF status in the dialog box. 
Script was updated with safeguards for passwording out so information is not lost.

Resolved #2437 entire script updated

---

Script Files/NOTICES/NOTICES - MAIN MENU.vbs
Script Files/NOTICES/NOTICES - OUT OF STATE.vbs

blip: 'This script will generate a word doc notice for out of state inquiry. added button to main menu.'

Resolves: #2053: 'patching out of state script with main menu commit'

---

COMPLETE LIST OF SCRIPTS.vbs
Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/BULK/BULK - SPENDDOWN REPORT.vbs

Blip - 'New script that will create an Excel spreadsheet listing information about cases that appear to have a spenddown in MAXIS.'
Ok - lets try this thing again.

Resolves #2523 - New spenddown report

---

Script Files/BULK/BULK - SPENDDOWN REPORT.vbs

Little more logic. No blip as this is a new script and just a bug fix. 
Also a typo.

Resolves #2535 - Fix bug in Spenddown report

---

Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs

BLIP: Fixed a bug that was not allowing users to apply manual student option due to WREG coding restriction. Updated handling to allow the appropriate WREG coding for students (FSET code "12").

Resolved #2538, SNAP E & T letter bug - student manual referral option

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs

BLIP: Added boolean variable in order for agencies to determine if SQL is being used to collect their data.

Resolved #2540, Added using_SQL_database variable

---

Script Files/BULK/BULK - REVS SCRUBBER.vbs

Blip - 'The script was missing some cases when scheduling. Fixes the logic to make sure all cases are selected that should be.'

Resolves #2534 - Bug fix to REVS Scrubber - missing cases

---

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs

BLIP: Script can now accurately handle memb panels where the age of the child is blank due to being under 1.

RESOLVES #2550 Adding handling for newborns

---

Script Files/NOTES/NOTES - GRH - NON-HRF-POSTPAY.vbs
Script Files/NOTES/NOTES - MAIN MENU.vbs

BLIP 'Case note script that will screen into non-hrf GRH cases and process GRH post payment.'

RESOLVES #1730 and #2205: creating new file

---

Script Files/NOTES/NOTES - MAIN MENU.vbs

BLIP:  Making the GRH NON HRF Postpay button display correctly.

RESOLVES #2559 Added spaces to fix grh button

---

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs

BLIP: Adding logic to avoid case noting confusing lines about programs closing when those programs are not on the case.

Resolves #2565 -- Fixing CASE/NOTE

---

COMPLETE LIST OF SCRIPTS.vbs
Script Files/UTILITIES/UTILITIES - COPY CASE DATA.vbs

BLIP: Adding the "Inverse Krabappel" script file. This script will grab case data from a training case and/or production cases, and will put the data into an Excel spreadsheet. For the script to run all the way through, you need to use a Krabappel template. The script is programmed to run with the data validation on the cells. INSTRUCTIONS TO COME!!!

Resolves #1142 -- Creating Inverse Krabappel

---

Script Files/NOTES/NOTES - CSR.vbs

BLIP: This pull request makes the NOTES ON INCOME field mandatory.

Resolves #2551 -- Making Notes on Income on CSR script mandatory

---

Script Files/BULK/BULK - DAIL REPORT.vbs

Blip - 'The DAIL Report will now create a second worksheet in the Excel report that has counts for each worker's DAILs, including total DAILs and any of the DAIL types selected.'

Resolves #2574 - DAIL Report with Counts 

---

Script Files/DAIL/DAIL - FIN ORIENT MISSING.vbs

Fixes a critical error - my original pull went horribly wrong.

Resolves #2581 - Financial Orientation Date DAIL

---

Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs

BLIP: Code was left in locking new scrubber behind master branch global variable

fixing master branch issue

---

Script Files/DAIL/DAIL - FIN ORIENT MISSING.vbs

Issue #2581 - critical

---

Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs

BLIP: removing master only restriction and removing link to old scrubber

RESOLVES #2587 Removing old CSES scrubber

---

Script Files/BULK/BULK - MAIN MENU.vbs
Script Files/BULK/BULK - REPT-INTR LIST.vbs

Blip - 'New Script that creates a report from REPT/INTR. Excel report generated with each item from INTR and a second worksheet with counts for each worker. Script includes the option to enter a supervisor X-Number and have all workers numbers listed under that supervisor checked.'

Resolves #2573 - Bulk Report for PARIS Matches

---

Script Files/NOTES/NOTES - COUNTY BURIAL APPLICATION.vbs

Blip - 'Update to the script that will autofill date of death and asset information from STAT. New fields for case noting additional detail including service type, place and amount. Place for contact person information. The script now has an option to create a Word Document with information about the application as much of this process happens outside of MAXIS.'

Resolves #2577 - Enhancement to County Burial Application

---

Script Files/NOTES/NOTES - HC RENEWAL.vbs

added move_verifs_needed 
Gave agencies the option to have verification's needed at the top or the bottom of the case note.

Resolved #2607 Enhancement for NOTES- HC REVIEW

---

Script Files/NOTES/NOTES - HCAPP.vbs

added move_verifs_needed 
Gave agencies the option to have verification's needed at the top or the bottom of the case note.

Resolved #2606 Notes - HCAPP

---

README.md

fixing date and adding veronica as backup

RESOLVES #2638 fixing date/adding backup

---

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs

BLIP: This enhancement makes the script check for an additional line for ADDITIONAL APP when checking PND2.

Resolves #2642 -- Adding Additional App check for denying from PND2

---

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs

Will now case note the MEMB #, CS type, and the amount per person receiving CS.

Resolved #2624: CSES scrubber enhancement.

---

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs

Blip: Corrects a bug that sometimes prevented the script from updating UNEA panels in the correct footer month.

Resolves 2646 CSES scrubber footer month.

---

COMPLETE LIST OF SCRIPTS.vbs

BLIP: This update removes GRH HRF from the list of all MAXIS scripts.

Resolves #2652 -- Removing NOTES - GRH HRF from Complete List

---

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs

BLIP Adding two counties (Morrison and Pine) that are exempt from snap e&t to the list of exempt counties

RESOLVES #2663 Adding morrison/pine

---

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs

This fully resolves 2646 Unea will now be updated correctly on all cases.

Resolves #2646 #2666 CSES scrubber footer month.

---

Script Files/DAIL/DAIL - ES REFERRAL MISSING.vbs

Blip - 'Fixes a bug that prevented the script from updating EMPS'

Resolves #2597 - ES Referral date

---

bulk/main-menu.vbs
notices/main-menu.vbs

This should be the last one for the night!

final fixes for bulk and notices

---

actions/fss-status-change.vbs

Blip - 'New script that will update all panels to change a case to FSS using client documents or a Status Update. Script will update all STAT panels as needed for the particular FSS category, case note, and TIKL.'
Note - this was not done in just one commit but the name had to be changed and so looks like only one commit. 
Second note - the list of scripts is updated on my next pull to allow the script to be accessed in the actions menu - wanted to avoid a merge conflict .

Resolves #2371 - New Script FSS Status Change

---

Script Files/ACTIONS/ACTIONS - CHECK EDRS.vbs
Script Files/ACTIONS/ACTIONS - SEND SVES.vbs
Script Files/BULK/BULK - REPT-ARST LIST.vbs
Script Files/NOTES/NOTES - EDRS DISQ MATCH FOUND.vbs

Adding these to see if we are pointing to the capital scripts or the lower case ones

Adding random message boxes

---

actions/paystubs-received.vbs

Removed PF3 after case note to give the option for worker to PF10 to remove the case note after running script.

Issue #2717 Updated Paystubs Received to end script on case note

---

notes/csr.vbs

Adding the option for Agencies to put verification's needed at the top of case notes instead of the bottom.

Added global var option to move verifs needed to the top

---

notes/hrf.vbs

Added checkbox for indicating HRF is being processed for MSA program.

Issue #2647- HRF updated to add MSA checkbox

---

bulk/check-snap-for-ga-rca.vbs
notes/ievs-match-received.vbs
notes/main-menu.vbs

Changing the verbiage from notice to match for NOTES-IEVS as this makes more sense to workers.

#2760 NOTES - IEVS verbiage change

---

notes/county-burial-application.vbs
notes/county-burial-determination.vbs

Corrected Typo on word Creamation to cremation

#2763 Cremation typo fix

---

notes/grh-non-hrf-postpay.vbs

#2740 changed to "facility name, GRH payment for month/year" rather than "facility name, billings for month/year"

Changing Case note title to read better

---

actions/pa-verif-request.vbs

Adjustment to making the word document leave out the income from STAT. This is to better serve our clients and protect data.

#2762 Option on PA Verif Request to not list income

---

notes/hrf.vbs

HRFs now have a separate dialog and functionality specific to LTC,

#2769 - LTC Functionality for NOTES - HRF

---

dail/cses-scrubber.vbs

Added datepart to pull only the month portion to evaluate for it's length. Going to commit to release shortly.

Fixing month bug

---

notices/appointment-letter.vbs

Appointment time variable was not being written if case wasn't phone interview.

Fixing appointment time bug

---

bulk/rept-actv-list.vbs
bulk/rept-pnd2-list.vbs

Added all changes into the change log for REPT/ACTV and REPT/PND2

#2786, #2651, #2611 Bulk reports

---

actions/hg-expansion-mony-chck.vbs

Added handling for significant change cases. The navigation in ELIG is a little different.
Added handling for cases where the issuance that eligibility worker can approve has been exceeded (when this occurs, supervisors need to approve the issuance).

#2791 Housing grant enhancements

---

bulk/address-report.vbs

#2592 adding homeless code to excel file

Adding homeless code

---

dail/cses-scrubber.vbs

A few things I found here and there to help the script run better for workers.

#2799, #2800, #2801 - CSES Scrubber

---

COMPLETE LIST OF SCRIPTS.vbs
utilities/copy-case-data-for-training.vbs

Identity crisis utilities

---

utilities/copy-case-data-for-training.vbs

Fixing loop missing clause

---

notices/method-b-wcom.vbs

Adding option to write to a memo if a waiting notice is not found.

Adding memo to method b wcom

---

bulk/non-magi-hc-info.vbs

@MN-Script-Team/maxis-scriptwriters could I get someone to test this in ACTV, and REVW? I just want to see that the column (N) is being filled in correctly. Thank you!

Adding new column to check for HC status

---

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Added correct handling of DWP disqual and improved noting.  New Sanction status for DWP disqual that makes sanction percent, number of sanctions, and pre/post 60 not mandatory fields when selected.   Also removes calculation of last day to cure sanction for DWP cases, as there is technically no last day to cure for DWP.

resolves #2806 MFIP Sanction / DWP disqual policy issues

---

bulk/update-eomc-list.vbs

Changed initial dialog to a msgbox and added cancel handling.

Bug on BULK - Update EOMC

---

notes/mfip-sanction-and-dwp-disqualification.vbs

Original pull was entered in wrong directory, please pull this in here

changed it was in the wrong directory

---

actions/fset-sanction.vbs

Added Changelog, Updated dialogs to reflect banked months vs. ABAWD extension, new reason for sanction reasons, removed MAXIS footer month/year and using sanction month/year instead, updated dialog do loops and case notes to reflect changes in dialogs/variables, added footer month confirmation based on sanction date variables, added reason for sanction field completion into STAT/WREG panel.

#2780 -  FSET saction updates

---

bulk/ltc-grh-list-generator.vbs

# 2816 LTC GRH list generator

---

notes/documents-received.vbs

removing defined datestamp

---

utilities/copy-case-data-for-training.vbs

wrong number of arguments were being used.

fixing message box bling

---

dail/dail-scrubber.vbs
notes/caf.vbs
notes/combined-ar.vbs

Adding option to offer a TIKL if the script detects a SNAP case with a renewal days over 12 months away

Tikl for 24 months

---

notes/caf.vbs
notes/combined-ar.vbs

Spelling error

---

actions/paystubs-received.vbs

BLIP: The script is now capable of handling the GRH PIC on JOBS and case noting that it has been updated.

In RE 2868 - GRH PIC to Paystubs Received

---

notes/mnsure-retro-hc-application.vbs

My county is having NetMotion issues at my county, so I can't access GitHub desktop or anything else for that matter. Did not test, but pretty confident it's working.

#2798 Changed verbiage from Curam to METS

---

notes/es-referral.vbs

added program type to case note header
Cleaned up old code, updated appt date condition in do loop, added ES
provider to case note, updated variable from program to select_program
in case note

#2797 Es referral 

---

notes/csr.vbs

BLIP: The script has been updated to clean up the case noting. It was case noting Verifs Needed twice.

RE #2846 Updating Case Noting in CSR

---

COMPLETE LIST OF SCRIPTS.vbs
notices/client-death-wcom.vbs
notices/duplicate-assistance-wcom.vbs
notices/main-menu.vbs
notices/returned-mail-wcom.vbs

Adding New wcoms death, returned mail, out of state dup assistance

---

actions/fset-sanction.vbs

No longer blanks out number of sanctions, and reason for sanction.

#2851 FSET sanction- resolved sanction

---

dail/cses-scrubber.vbs

Adds msgbox with yes/no to ask the user whether they want to update on cases where SNAP / MFIP are not open.

CSES scrubber update for HC only cases #2714

---

Script Files/SETTINGS - GLOBAL VARIABLES.vbs
locally-installed-files/SETTINGS - GLOBAL VARIABLES.vbs

Adding the changelog_enabled variable to Global Variables so counties can select their option for thi feature.

#2856 ChangeLog Option added to Global Variables

---

notes/ltc-asset-assessment.vbs

Tested and working. I can test again in Master once pulled.

#2629 Aa updates

---

notes/denied-programs.vbs
notices/abawd-with-child-in-hh-wcom.vbs
notices/banked-months-wcoms.vbs
notices/client-death-wcom.vbs
notices/duplicate-assistance-wcom.vbs
notices/ma-epd-no-initial-premium.vbs
notices/ma-inmate-application-wcom.vbs
notices/method-b-wcom.vbs
notices/postponed-wreg-verifs.vbs
notices/returned-mail-wcom.vbs

Corrected a bug in numerous scripts to handle new recipient selection screen on SPEC/WCOM.   The following scripts were updated:
MA Inmate Application WCOM
MA-EPD No Initial Premium Paid
Method B WCOM
ABAWD with child in HH WCOM
Banked Month WCOMS
Client Death WCOM
Duplicate Assistance WCOM
Postponed WREG verif.
Returned Mail WCOM
Denied Programs (checkbox to add requested verifs to WCOM)

Updates for SPEC/WCOM changes, #2906 and #2905

---

notes/denied-programs.vbs
notices/abawd-with-child-in-hh-wcom.vbs
notices/banked-months-wcoms.vbs
notices/client-death-wcom.vbs
notices/duplicate-assistance-wcom.vbs
notices/ma-epd-no-initial-premium.vbs
notices/ma-inmate-application-wcom.vbs
notices/method-b-wcom.vbs
notices/postponed-wreg-verifs.vbs
notices/returned-mail-wcom.vbs

This pull contains only commits that update the WCOM scripts as referenced in #2906. Update for release branch.

Fixing WCOM scripts from #2906 

---

notes/expedited-screening.vbs

I wanted to pull in #2985 but ran into issues because of (what I believe was) a whitespace problem with @C-Love's setup. Rebuilt it manually.

#2968: manually resolving issue with HEST standards

---

notes/lep-sponsor-income.vbs

Note that this originally was done by @c-love but because GitHub was acting weird I had to redo it.
Testers, are you ready? @C-Love? @IlseFerris?

#2944: sponsor income limit update

---

notes/lep-sponsor-income.vbs

Added correct multiplier amount on line 113 to reflect current income standards.

Resolved #2944 - Updated income standard

---

actions/transfer-case.vbs
bulk/case-transfer.vbs
bulk/memo-from-list.vbs
bulk/revs-scrubber.vbs
dail/fmed-deduction.vbs
dail/send-nomi.vbs
notes/closed-programs.vbs
notes/interview-no-show.vbs
notes/significant-change.vbs
notices/12-month-contact.vbs
notices/appointment-letter.vbs
notices/eligibility-notifier.vbs
notices/grh-op-cl-left-faci.vbs
notices/method-b-wcom.vbs
notices/mfip-orientation.vbs
notices/mnsure-memo.vbs
notices/nomi.vbs
notices/overdue-baby.vbs
utilities/copy-case-note-elsewhere.vbs

19 Files changed to update functionality to so that scripts can once again send SPEC/MEMOs.

#2995 - Addressing SPEC/MEMO Bug 

---

bulk/case-transfer.vbs
bulk/exp-snap-review.vbs
bulk/housing-grant-exemption-finder.vbs
bulk/rept-actv-list.vbs
bulk/rept-eomc-list.vbs
bulk/rept-inac-list.vbs
bulk/rept-mams-list.vbs
bulk/rept-mfcm-list.vbs
bulk/rept-mont-list.vbs
bulk/rept-mrsr-list.vbs
bulk/rept-pnd1-list.vbs
bulk/rept-pnd2-list.vbs
bulk/rept-revs-list.vbs
bulk/rept-revw-list.vbs
bulk/spenddown-report.vbs
bulk/targeted-snap-review-selection.vbs

There are a number of bug and enhancements for BULK scripts. This pull will resolve them.
- Missing cases on large runs
- Allows for supervisor to use their own x-number to pull all workers under them
- Additional Applications listed in PND2 causes missing cases
- MFCM misses cases due to second care giver
- Add functionality to pull REVS for any month

BULK Scripts Fix - #2970, #2843, #3005, #3006, #2889

---

notes/ltc-1503.vbs

This update fixes a type mismatch error with HCMI_panel_check.

RE #2899 - Correcting type mismatch error

---

notes/evf-received.vbs

Added employer name to Tikl. 
(Initial pull request did not contain the update.)

Issue 2716 EVF Received Updated

---

notices/snap-e-and-t-letter.vbs

Resolved multiple issues/updates: Multiple updates include handling for multiple household members, background check, removed exempt counties coding, added other manual reason info into case note, upated TIKL msgbox, and added ABAWD to manual referral droplist.

#2959, #3017, #2989, #2962, #2917, #2961, #2916 SNAP E & T LETTER: All the issues

---

dail/cses-scrubber.vbs

Statistics are not correctly calculating- added a stats counter incrementer.

Issue #2890 and #2912 adding counter for stats and handling for lot-o-dails

---

notices/method-b-wcom.vbs

Fixed NOTICES Method B WCOM script so that it looks for the Method based on the month indicated instead of defaulting to the first month in the ELIG period.

Issue #2895 - Method B WCOM 

---

notes/application-received.vbs

Enhancement to NOTES - Application Received. Add day 30 to case note, enhanced time formatting, allowing for adding internal routing dates.

Issue #2972 - Update App Received

---

bulk/case-transfer.vbs

Add enhancement to allow search to filter by recently closed programs  (note I have changed my tab settings so much of the changes indicated in the diff are due to that change in atom)

Issue #2906 - BULK Case Transfer

---

actions/fss-status-change.vbs

Fixing bugs - dialog length, date format issue, and a check for background.

Issue #2971 - Bugs on FSS Status Change

---

actions/paystubs-received.vbs

Script corrected to allow user to enter paystub for current date.

Resolved #2956

---

dail/new-hire-ndnh.vbs

Script updated to support INFC requirements.

#2966 Other part of the issue: DAIL - NEW HIRE NDNH

---

dail/tyma-scrubber.vbs

Rreading dates changed to 10 digits so that the year is not always 20

#2993 - TYMA TIKLS should not be 3 years from now

---

bulk/revw-mont-closures.vbs

Removing HC app line from case notes because it is not correct.

#2875 REVW/MONT Closure

---

notes/ltc-application-received.vbs

Fixing bug that crashed the script if a TIKL was attempting to be set for an old case.

#2901 - LTC App Received
