MN-Script-Team/DHS-MAXIS-Scripts

Script Files/NOTES/NOTES - CSR.vbs
Here's what I changed:
* Added `eDRS_sent_checbox` and handling for case/note.
* Modified `_check` to `_checkbox` where relevant, to match what I teach
scriptwriters now.
* Added a "select one..." option in the CSR_status dropdown, so that it
doesn't default to complete. Also modified the handling of the do...loop
accordingly.
* Indenting is now the prettier tab instead of the uglier double
spacing.
* Removed an unneeded ERRR check. `navigate_to_screen` does it for you
now.
* Modified all case note functions to match the latest and greatest in
FuncLib.
Tested and working. This resolves #333. Woohoo!
=> CSR updated

Script Files/MEMOS/MEMOS - MAIN MENU.vbs
Because Hennepin is (at least temporarily) scheduling appointments in a
time-range (instead of a specific time), and they (at least temporarily)
have permission to do this, the NOMI and Appointment Letter scripts
might technically provide incorrect notice to clients, which could
create policy errors. So, I am temporarily removing access to them from
Hennepin users. If Hennepin is to use this same method in the near
future, separate versions of these two scripts may be deployed to allow
for a range of times.
=> Added Hennepin handling to remove two scripts

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs
Changed logic to follow 4 month renewal change to policy. HC_intake_date was still filling in as first of month after renewal. (for 03/15 renewal 4/1/15.) Tested this on MAGI, non_magi, and no HC cases.
=> Revw mont fix2

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs
This fix reflects the change in policy from Bulletin #14-69-05 (allowing a reinstatement period for cash recertifications -- not RCA)
If the client is closing on a recertification (NOTE: NOT MONTHLY RENEWAL) for GA, MSA, MFIP, DWP, or GRH, the client is eligible for an additional reinstatement period. The script now goes to STAT/PROG, from STAT/REVW, to determine if the client is active on any of those 5 programs, and adds an additional calendar month to the variables "last_day_to_turn_in_cash_docs" and "cash_intake_date".
=> Revw mont closure fix

Script Files/NOTES/NOTES - LTC TRANSFER PENALTY
LTC Transfer Penalty case note.  Gives template to LTC worker in which to case note the details of a transfer penalty.  Script will also case note and automatically case note the lookback period based on the baseline date.  Case note also pulls in the Uncompensated Transfer Calculator from MAPT, and case notes this information.
=> Create NOTES - LTC TRANSFER PENALTY

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
Quick update to add DateDiff for start of MFIP Housing Grant. 
The way that the script builds the MFIP grant line (lines 313 through 357) is now contingent upon the benefit month.
The way that the script case notes the MFIP grant (lines 533-545) is now contingent upon the benefit month. 
See MAXIS Training Case #222211 for an example. All good!!
=> Approved progs accounting for mfip housing grant start date

Script Files/BULK/BULK - LTC-GRH LIST GENERATOR.vbs
Moved last page check before the nested do.
When you get to the last page on REPT/ACTV, "THIS IS THE LAST PAGE" is displayed. The way the script was programmed, it was reading "THIS IS THE LAST PAGE" immediately after the PF8 and it prevented the last page from being read.
=> Update BULK - LTC-GRH LIST GENERATOR.vbs

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs
Changes apply to case transfer within agency logic...
*  Added "Select one..."+chr(9)+"N/A"+chr(9)+ to the DropListBox for unit and pregnancy verif. In both cases, the information may not be necessary.
*  Also updated the logic for the case noting to case note the incoming unit and pregnancy verif information when those variables are not "N/A"
=> Quick Fix to ACTIONS - TRANSFER CASE

Script Files/BULK/BULK - MAIN MENU.vbs
Created new BULK Main Menu. The old main menu was getting too big. This format can be used to consolidate the NOTES main menu using alpha-split tabs.
A button was also built for a new script that will be pulled with an separate pull request -- CHECK SNAP FOR GA/RCA.
=> Update BULK Main Menu

Script Files/ACTIONS/ACTIONS - SEND SVES.vbs
Added double-quotes around the SSA agreement script end procedure. The bug is creating a syntax error.
=> SSA agreement fix

Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Things that are updated...
- PIC_paystubs_info_adder function
---> Modified PIC handling to allow for second page
- Created create_paystubs_received_dialog function
---> Allows the script to handle as many pay dates as the user needs 
---> Resolves #91 
- Modified order of dialogs
---> User selects the household member and the job BEFORE entering pay information
---> User has the option of changing the household member during the script if all jobs for the current household member are rejected
- Created dialog and modified DO/LOOP to have script figure out which day of week to use for prospecting income
- Added MsgBoxes to warn users of problematic scenarios
---> Does not allow the user to enter future pay dates (resolves #572 )
---> If the user is trying to enter more than 10 pay dates, …
=> Updating PAYSTUBS RECEIVED

Script Files/NOTES/NOTES - LTC - 1503.vbs
Resolves issue #895 
Was overwriting current faci.  Put in logic to 1. stop the script from
overwriting the current faci. 2. stop the script if 5 FACI panels are
present (the max amount of panels), and instructs the worker to delete a
FACI panel and run the script again.  Also update MAXIS check, added
background check and reordered how the script runs to accommodate the
script ending if 5 faci panels exist.
=> 1503 critical bug fix

Script Files/BULK/BULK - ADDRESS REPORT.vbs
Worker number was being converted to add worker_county_code to the x_number variable no matter if it was already there or not (for solo runs). Tested on solo and batch and it seemed to work.
=> Worker number issue

Script Files/ACTIONS/ACTIONS - BILS UPDATER.vbs
Took out the function "CREATE_PANEL_IF_NONEXISTENT()" and created new
logic to do the following:
1. stop the script if case is in another county or HC is not active
prior to main dialogs being filled out
2. create a BILS panel if one does not exist and HC is active or pending
3. go into edit mode if BILS panel already exists.
This resolved issue #948 
Tested and good to go!
=> BILS updater bug fix

Script Files/ACTIONS/ACTIONS - LTC - SPOUSAL ALLOCATION FIATER.vbs
resolves issue #960 
updated the FuncLib path (Op Doubtfire)
updated dialog to include instruction to process manually if LTC spouse
is open on CASH programs
Added correct coding for UNEA and JOBS income.  Codes income codes from
STAT panels, and the LTC spousal allocation pop up differ.
=> Ltc spousal allocation fix

Project Krabappel/BULK - project Krabappel.vbs
Changing order of write_panel_to_MAXIS function calls. Now ABPS is going after PARE (because write_panel_to_MAXIS_ABPS pulls children numbers and parent number from PARE).
Resolves Issue #1032
=> Update BULK - project Krabappel.vbs

Script Files/MEMOS/MEMOS - SNAP E AND T LETTER.vbs
LOOP did not appears to have an IF prior to the county codes that are
manual entry.  Tested and working.
=> SNAP E & T letter fix for manual address input-resolves issue #1037

Script Files/NOTES/NOTES - EXPEDITED SCREENING.vbs
Resolves issue #1040 
Here’s how the script differs from the original:
If the client appears expedited, the script will go to the MONY/DISB screen and reads the MAXIS screen to see if the client has an EBT account open or not.
If the code is “N” then the following verbiage has been added to the case note “EBT Account is NOT open. Recipient is able to get initial card in the agency. Rapid Electronic Issuance (REI) can be used, but only to avoid an emergency issuance or to meet EXP criteria."
If the code is “Y” then the following verbiage has been added to the case note “EBT Account IS open. Recipient will be able to get a replacement card in the agency. Rapid Electronic Issuance (REI) with caution."
=> Exp snap ebt info enchancement

Script Files/NOTES/NOTES - DWP BUDGET.vbs
Updated the script to make the number of DWP HHLD members a mandatory field so the personal needs calculation runs without errors. The do loop was changed to give the worker an error message if mandatory fields not entered. 
Also made slight adjustment to the spacing of the fields in the dialog box so they were no longer overlapping.
=> Update NOTES - DWP BUDGET.vbs

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs
There was a syntax issue that we haven't noticed until now.
This addresses issue #1079
=> Fix to MFIP fiating procedure

Project Krabappel/BULK - project Krabappel.vbs
The pop-up for "Do you want to continue with approval" is not where Krabappel needs it to be. This fix replaces EMReadScreens with EMSearches
=> Update to SNAP Approval logic

Script Files/NOTES/NOTES - CSR.vbs
Here is the warning:
If you select "Is this an exempt IR", the case note will only read that
the paperless IR was cleared (no case information listed).
If you are processing a CSR with SNAP, you should NOT check that option.
This resolves issue #1041
=> updated dialog box with an exempt IR checkbox warning

Script Files/NOTES/NOTES - HCAPP.vbs
#1028
I updated the DO loop to account for longer than 10 digit datestamps and warning the worker on the dialog they made the error on. removed the tikl/pnd2/case note functionality out of the do loops.
updated function block
tikl function not updated(did not mess with Tikling already hard coded in there as it works already and is designed around pre functions)
spec/memo not updated, does not spec memo
write_variable_in_case_note seems to be already updated
check_for_maxis, already updated
nagivate_to_maxis, updated to new function
MAXIS_dialog_nav, deleted old button functions
=> Update NOTES - HCAPP.vbs

Script Files/MEMOS/MEMOS - MAIN MENU.vbs
from MEMO to SPEC/LETR.  I can't tell you how many people report that the script isn't working because they go to SPEC/MEMO instead of SPEC/WCOM to see the correspondence.
=> Updated verbiage on the SNAP E & T letter description

Script Files/NOTES/NOTES - CSR.vbs
* Split dialog into 2 dialogs (we were hitting the 65 object limit)
* Added err_msg handling around mandatory dialog fields (CSR_datestamp, CSR_status, HH_comp, earned_income-unearned_income-notes_on_income, actions_taken, worker_signature)
* Added previous button to second dialog to allow users to review work on page 1.
=> Many updates to CSR (see notes)

Script Files/NOTES/NOTES - HC RENEWAL.vbs
#561  CAF seems to be pulling footer months, CSR also autofills, as does CAR. HCAPP was fixed in previous version.
=> Fix for footer month issue

Script Files/BULK/BULK - REPT-PND2 LIST.vbs
The script is writing the entire 7-digit worker number when running for the entire agency.
=> Patch to PND2 list

Script Files/BULK/BULK - REPT-PND2 LIST.vbs
The script is making sure to write the worker number in the correct place. Works for both agency-wide and individual look ups.
=> writing the worker number

Script Files/NOTES/NOTES - HCAPP.vbs
The script was subtracting 2000 from the benefit year when all it needed to do was read the right 2 of the benefit year. This was generating a result of benefit_year = -101.
Resolves issue #1151
=> Simplifying auto-fill of benefit year

Script Files/NOTES/NOTES - HCAPP.vbs
footer_year was being determined from an unknown variable (which is why it was originally delivering footer_month = -101
I didn't notice it in my haste. Now, footer_year is determined from date
=> next_month not defined, adjusted for date

Script Files/DAIL/DAIL - CS REPORTED NEW EMPLOYER.vbs
Script was getting stuck trying to back out to SELF. New custom functions prevented the script from functioning as it was originally designed. The Operation Doubtfire gave the script a shiny new turbocharger, this upgrades the cooling.
=> Updating navigation in CS New Job

Script Files/BULK/BULK - LTC-GRH LIST GENERATOR.vbs
A bug was reported via email and confirmed. The script was stopping without generating a list. There was a stopscript hiding in the code.
=> Removing a stopscript in LTC/GRH LIST GEN

Script Files/NOTES/NOTES - VERIFICATIONS NEEDED.vbs
This update fixes the script not including the case worker name in the case note.
Issue # 1158.
The TIKL part of the script is working as intended. It brings the worker to where they can enter their TIKL. The msgbox tells the worker what they are supposed to do at this point.
=> Update NOTES - VERIFICATIONS NEEDED.vbs

Script Files/NOTES/NOTES - COMBINED AR.vbs
Fixed incorrect variables, removed MAXIS_footer_finder as it seems to be working incorrectly. I will test but the function seems to be reading 11 off of MAXIS and then it asks isnumeric and it is saying it isn't. Function is likely reading in a string so the variable the function finds will never be a number and always default to CM.
#1204
=> Fixing footer month and renewal month issue

Script Files/BULK/BULK - REPT-ACTV LIST.vbs
this script would not work for multicounty agencies. now it should. I inserted the function that does stuff to reduce multicounty to a single 2-digimon county code
=> reinstating multicounty functionality

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
This update includes the following fixes, addressing issues #1217 and #1220.
1. err_msg handling around dialog (Operation Wind Tunnel)
2. Updated verbiage in notice to reflect October start date for CS Disregard (rather than July) and also removing typo.
3. Added do...loop around search for appropriate WCOM when user selects to case note that the CS disregard verbiage should be added to notice.
4. Updated case note verbiage to case note only when script actually updates a notice (currently, it is case noting that the cs disregard verbiage was added to the notice even if the script did not add one...there are instances when a new notice is not generated).
=> several fixes to NOTES-APPROVED PROGRAMS (see below)

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
now the script will case note "EXPEDITED SNAP" instead of just "SNAP" in the header, and it will case note that there are verifs still needed on the case.
resolves #1219
=> added postponed verif check to Approved Progs

Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs
Bugs fixed include footer month not filling itself in, and when user
would push the cancel button  the case was going through MAXIS
navigation.  Also cleaned up a couple functions.
=> Fixed bug when canceling script & footer month

Script Files/NOTES/NOTES - CAF.vbs
Prevents the user from just defaulting to the 1st option, which is
intake.  Also added case number function, and cleaned up a few spaces.
Resolves issue #1174
Blip for release notes: Enhancement to the initial dialog.  A "Select one..." option was added to the CAF type field to prevent users from defaulting to the first option (intake).
=> inserted select one as option in CAF_type droplist

Script Files/NOTES/NOTES - EXPEDITED SCREENING.vbs
Op Doubtfire replaced some code that was in place to prevent an infinite loop that start_a_blank_case_note causes when someone uses an incorrect case number or out of county case number. Took code from #967 and reincorporated it with recent enhancements. 
BLIP: Expedited screening tool can once again be used on out of county cases or cases without a case number (enter 1 as case number if client doesn't have case.)
fixes issue #1273
=> Bug fix/reverting code

Script Files/MEMOS/MEMOS - NOMI.vbs
Resolves #1062 
Blip: Adds an optional field to the NOMI dialog and case note for documenting attempts made by the worker to contact the client.
=> MEMOS - NOMI adds "attempts to contact client"

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs
Resolving issue #1149
Made some changes to the dialog box, with more option:
-added a few more checkboxes.
-add check option for consecutive sanctions - because resolution date is treated slightly different
-'Removed the droplist for number_occurances and changed that to editbox for worker to enter then # of sanctions
Added where after case notes, if checked & MFIP is approved, it'd go fill in SPEC/WCOM.
Added a checker for the sanction date to = mm/01/yyyy
Dim Resolution_date so it's a place holder variable for case noting and calculating dates.
Also added date calculation for the right date to resolve sanction by.
=> Update NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs

Script Files/ACTIONS/ACTIONS - CS DISREGARD FIAT.vbs
Resolves #1321  Removed <> "APP CLO" from the program checks on CASE CURR, changed logic to look at DWP, and if no version to look at MFIP.  (For when transitioning from DWP to MFIP. This is the only "APP CLOSE" situation I could think of that would cause an error.)  @RobertFewins-Kalb can enlighten us on Monday if there is still an issue.
=> Update ACTIONS - CS DISREGARD FIAT.vbs

Script Files/DAIL/DAIL - NEW HIRE.vbs
BLIP: Script will now end and prompt user to clean up jobs panels if there are already 5. (MAXIS has a limit of 5 jobs panels per person).
#1328
=> Adding check to for 5 jobs panel

Script Files/DAIL/DAIL - NEW HIRE.vbs
BLIP: Cancelling the script would lead to an infinite loop because of MAXIS_dialog_navigation function. Added a do/loop and reordered functions so they work in tandem. 
#1354
=> Fixing cancel_confirmation bug

Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs
With the shrinkage at 45 the information of the bottom was getting cut
off. 65 covers the entire information message at the bottom (which is
necessary if it's not an intake case noting agency).
BLIP: Resized the dialog box for agencies that do not case note intake dates to not display the partial CM reference. 
resolves #1385
=> variable to resize dialog changed from 45 to 65

Script Files/ACTIONS/ACTIONS - MA-EPD EI FIAT.vbs
BLIP: Script can not navigate to jobs panel for selected memb rather than whoever it finds by typing stat/jobs without entering a member number
Tested on a few MA-EPD cases.
#1392
=> Adding MEMB # handling

Script Files/MEMOS/MEMOS - POSTPONED WREG VERIFS.vbs
BLIP: Script will now TIKL for 10 days from date to remind worker to close case. Here is a example of the TIKL "Verification of postponed WREG verification(s) should have returned by now. If not received and processed, take appropriate action."
#1393
=> Adding TIKL

Script Files/DAIL/DAIL - ABAWD FSET EXEMPTION CHECK.vbs
This script can be run on PEPR message instructing the worker to shut down the case for ABAWD months. (FS ABAWD ELIGIBILITY HAS EXPIRED)
The script is a slightly modified version of ACTIONS - ABAWD FSET EXEMPTION CHECK. The script will check...
* MEMB for the client's age
* DISA for a disability status
* EATS (for minors in the EATS group and disabled HH members)
* JOBS/BUSI for total earnings and hours worked
* RBIC for RBIC (not adding to total earnings or hours)
* UNEA for on-going unemployment compensation
* PBEN for SSI application
* PROG for active cash
* PREG for active pregnancy
* SCHL/STIN/STEC for active school enrollment, student income, and student expenses
In RE: #1231
=> Creating script -- DAIL - ABAWD FSET EXEMPTION CHECK

Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs
Reading for "FS ABAWD ELIGIBILITY HAS EXPIRED" and running DAIL - ABAWD FSET EXEMPTION DOUBLE CHECK.vbs when it finds it.
In RE: #1231 
BLIP: This modification expands the DAIL scrubber to double check cases closing for ABAWD months for a possible exemption coded in MAXIS.
=> Adding access to DAIL - ABAWD FSET EXEMPTION CHECK

Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Blip: Script was skipping first job for members other than 01. Script will not no longer skip job 01. 
#1441
=> bug fix, writing jobs number for non mem 01

Script Files/BULK/BULK - REPT-REVS LIST.vbs
Resolves #1406 
BLIP: Adds two optional features to REPT/REVS pull data to excel to assist with auditing SNAP reviews for accuracy: Checks if an autoclose notice was sent, and enters info about the type of notice for auditing purposes, checks for errors in updating STAT/REVW by reading case/note so updates can be made before notices are sent.
=> Enhanced version of REPT/REVS

Script Files/DAIL/DAIL - CSES PROCESSING.vbs
BLIP: Script will now clear out the last name field on PESE. In addition if the script slowed down a bit during writing the SSN into PESE it had a chance to hit transmit before SSN was fully written. This has been fixed as well.
=> Bug fix, PESE not getting cleared #1505

Script Files/NOTES/NOTES - CAF.vbs
making both values strings to make sure they are being pulled into the dlg
Resolves #1534 
BLIP: Converting footer_month and footer_year to strings to make sure they are pre-populated in case_number_dialog when it loads.
=> Fix to footer month & year

Script Files/MEMOS/MEMOS - GRH OP CL LEFT FACI.vbs
BLIP: Script wasn't using the right variable to write the OP total amount. Now the script will take what is entered into the dialog for total and use it. Script will also calculate the total if the worker leaves the total field blank.
=> Fixes variable name issue #1538

Script Files/NOTES/NOTES - GRH - HRF.vbs
Because these are for post-pay, we are looking at retro. No need to default to prospective month. Case note header has already been updated to reflect this change.
Resolves #1515
BLIP: This update defaults the footer month and year to the retro month.
=> Footer month update to GRH HRF

Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs
BLIP: Script will case note some details about when a case closes for entering sanction if global variables case note intake dates. 
(Fixed dialog shrink issue and typo, I'm assuming it was a goof from pulling in and out of dialog editor.)
=> Adding sanction closure info #1394

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs
BLIP: Script now pays attention to the TIKL checkbox and will not tikl if not checked. Header for the case note correctly removes the extra / now.
=> moderning up some logic #1550

Script Files/MEMOS/MEMOS - POSTPONED WREG VERIFS.vbs
Resolves #1570
BLIP: This enhancement corrects an error caused by incorrect coordinates, allowing the script to get into the case in the correct benefit year.
=> Updating approval_year write coordinates

Script Files/NOTES/NOTES - LTC - MA APPROVAL.vbs
Resolves #1557
BLIP: This enhancement allows users to run the case on LTC cases where the eligibility type is AX.
=> Adding AX basis to LTC MA Approval

Script Files/NOTES/NOTES - LTC - 5181.vbs
BLIP: Script had type that cause it to be unable to PF9 on the SWKR panel. This has been fixed.
=> Bug fix, FP9 VS PF9 #1562

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
resolves #1528 and #1560 (sorry for the single commit / I developed and tested them together)
-Will now prompt the user to answer yes/no when determining whether to count items with verif code ?
-Prompts the user to answer yes/no to count income types "J", "E", "O", "I" "M" and "C" (all very rare, and aren't consistently coded on Jobs, so user input required)
-Automatically handles "W", "F", "S", "G"
=> handling for other income types and expedited

Script Files/DAIL/DAIL - CSES PROCESSING.vbs
BLIP: Script was incorrectly writing SSN by 1 digit.
related to #1561 (seems there are other issues tacked onto that one)
=> Bug Fix for writting SSN

Script Files/NOTES/NOTES - LTC - COLA SUMMARY 2016.vbs
BLIP: Updating the date check logic that is used to lock down the script when not in the appropriate footer month/year.
Resolves #1584
=> Updating date check for NOTES - LTC COLA SUMMARY 2016

Script Files/DAIL/DAIL - CITIZENSHIP VERIFIED.vbs
BLIP: Script was incorrectly writing one digit months and days. Used function to resolve this so script will no longer cause errors.
=> Replace emwritescreen with function #1595

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs
BLIP: Replacing an out of place character that is causing a critical error.
Resolves #1651
=> Replacing invalid character

Script Files/ACTIONS/ACTIONS - COPY PANELS TO WORD.vbs
BLIP: Removing an invalid character that is causing a critical error in the script.
Resolves #1653
=> Replacing invalid character from COPY PANELS TO WORD

Script Files/MEMOS/MEMOS - GRH OP CL LEFT FACI.vbs
BLIP: Script was incorrectly writing memos and possibly mailing to incorrect addresses if the client had any option other than OTHER on their new memo menu. Script will now search for the OTHER recipient option so it can properly write the address the worker enters.
=> BUG FIX: Added do loop to search for OTHER on new memo #1655

Script Files/NOTES/NOTES - MEDICAL OPINION FORM RECEIVED.vbs
Removing diagnosis language from Script due to HIPAA concerns. Text added to dialog, reminding workers not to enter diagnosis info in case note. Tab order reassigned to fix checkbox being out of place. One typo fixed in explanatory comment, because it bothered me.
=> Update NOTES - MEDICAL OPINION FORM RECEIVED.vbs

Script Files/DAIL/DAIL - CSES PROCESSING.vbs
BLIP: Adding additional check to make sure that the script exits a do when all the SSNs have been checked.
Resolves #1582
=> Adding error check to DAIL - CSES Processing

Script Files/BULK/BULK - INAC SCRUBBER.vbs, Script Files/SETTINGS - GLOBAL VARIABLES.vbs
BLIP: Split script into two paths, one that will retain MAGI cases closed for no/incomplete renewals (along with all previous qualities EX open in MMIS, unresolved dails messages, denials.) in current worker number. The other that will transfer the case to closed(after checking against previous qualities) even if it is a MAGI case closed for no/incomplete renewal. The script works in conjunction with the global variables set by each county agency so agencies can decide what works best for their workflow.
Resolves #364
=> Adding 4 month retaining to inac scrubber

Script Files/ACTIONS/ACTIONS - SHELTER EXPENSE VERIF RECEIVED.vbs
BLIP: Script can not handle transitions from subsidy shelter expenses.
=> fixing subsidy transtition issue #1680

Project Krabappel/BULK - project Krabappel.vbs
GA bene month was running through dateadd and turning something like 12/15 into 12/15/16
HCRE function is completely useless. If HC is added to TYPE MAXIS automatically navs to HCRE and enters the app info. We have no need to train on a retro case (and approval cannot handle that either) I removed the write to HCRE function. At this time I would suggest just striking through the HCRE portion on the excel spreadsheet and telling people not to fill it out rather than deleting the rows and reprogramming all of locations. The function also contained the now deleted MAXIS_dater function. Should we leave this in funclib for the time being or just delete the write to HCRE function?
=> Fixed GA bene month bug, and HCRE

Project Krabappel/BULK - project Krabappel.vbs
package approved variable needed to be reset for multiple SNAP approvals. 
MAXIS for some reason is filling in the GA in the SNAP fiat portion for 01/16 ongoing (maybe something changed in MAXIS?) added line to clear anything already written in there to FIAT the way we intended with that is stored in the array.
=> fixing GA bug, and UPS variable

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs
BLIP: script was occasionally derailing due for PF4/PF9 method of going to case note. Added function to fix this.
Resolves #1759
=> adding start a case note function

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Blip: Corrects a typo that was causing the phone deduction to be entered incorrectly on the garbage deduction line in FIAT.
Pulling to release as this could occasionally cause an incorrect budget to be entered.
=> Resolves #1755

Script Files/BULK/BULK - INAC SCRUBBER.vbs
BLIP: script was reading wrong number of characters causing problems on case loads with more than 1 page of inactive cases ran by that user.
Resolves #1774
=> Keep MAGI side was reading wrong # of characters

Script Files/BULK/BULK - INAC SCRUBBER.vbs
BLIP: Script was reading 3 characters from old days when we didn't require 7. Only affected on the keep MAGI side.
resolved #1774
=> Fixing characters read for keep MAGI side of inac scrub

README.md
The README has been modified: it now contains additional clarifying language about the definition of a critical issue. The new language basically says that admins can mark something as critical in other cases, such as panels being updated in MAXIS causing confusion.
=> Resolved #1796: updated definition of "critical" in readme

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Blip: Fixes a bug that was causing the script to fail to enter shelter deductions into the budget on some cases.
=> Resolves #1831 Bug with ABAWD Banked Months Fiater

Script Files/SETTINGS - GLOBAL VARIABLES.vbs
Blip: TYMA_TIKL_all_at_once has been added to the Global Variables file.
The default behavior both in the script and the Global Variables file is
to set this to false. Agencies installing or reinstalling scripts will
be able to modify this variable in the installer.
=> Resolves #1794: TYMA variable now included in GlobVar

Script Files/NOTES/NOTES - CAF.vbs
BLIP: Script will now correctly enter footer month and year into header of recerts. Also deleted extraneous CALL for new function as function doesn't carry variables through. 
footer_month and footer_year needed updating to MAXIS_footer_month and MAXIS_footer_year
=> Resolves #1860 Renaming footer month/year variable

Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs
Blip: Corrects a bug that prevented the script from sending a letter when a single digit hour was entered for the appointment time.  Corrects a typo that prevented the script from working for the Duluth office.
=> Resolves #1871 and #1872 NOTICES SNAP E&T LETTER bugs

Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs
"Blip: corrected spelling error on the manual referral for banked months recipients."
=> Resolves #1894, Spelling error on manual referral

Script Files/NOTES/NOTES - EXPEDITED DETERMINATION.vbs
Blip - 'Fixes a bug on the script that was causing an error when gathering asset information on some cases'
=> Resolved #1902: bug on Expedited Determination

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs, Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs
BLIP: Restricted access to Mahnomen county from using the SNAP E & T Letter and the ABAWD Banked months FIATer as they are an exempt county. 
Aitkin County (x101) was already excluded, just as an FYI
=> Resolves #1888, Exempt counties

Script Files/NOTES/NOTES - LTC - 1503.vbs
BLIP: Script wasn't able to go into edit mode on HCMI. Added in functionality. Moved check for maxis so script doesn't nav to stat/faci immediately after dialog without checking.
=> RESOLVES #1919 Fixing HCMI no edit bug

README.md
Blip: the README file has been updated to include a reference to our Slack team.
=> Resolved #1918: README.md now references Slack

Script Files/DAIL/DAIL - NEW HIRE NDNH.vbs, Script Files/DAIL/DAIL - NEW HIRE.vbs
Added feature to New Hire Dail Scrubber. When the script enters a Jobs panel, it checks for the "This Information will expire ..." which indicates that the JOBS panel will not carry forward to the next footer month. When this happens the script will now give you a Msgbox to alert the worker to check the next footer month.
=> Resolved #1821- Check for expiration

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
BLIP: Script will no longer search for SNAP or cash results if the user does not select the program checkboxes. It will also no longer case note unselected program results.
=> Resolves #1935 Making searching elig and noting conditional

Script Files/NOTICES/NOTICES - APPOINTMENT LETTER.vbs
BLIP: Added restriction for Hennepin County users. Restriction previously found in MEMOS - MAIN MENU, and has been moved to the script itself.
=> Resolved #1932, Appt letter restriction for x127

Script Files/NOTES/NOTES - CAF.vbs
BLIP: Script was updated to change variable name for footer month. this caused script to be unable to use functions that also didn't have this standard variable name updated. One the one reported function the script was unable to accurately reading the counted months off of WREG because footer_month was considered blank.
Script can now work with these functions to the fullest again.
=> RESOLVES #1941 fixing maxis footer month

Script Files/SETTINGS - GLOBAL VARIABLES.vbs
Blip: a slash was added to the `script_repository` variable if
`run_locally` is set to true. This makes the `script_repository` logic
match other scripts when testing DAIL Scrubber enhancements.
=> Resolved #1965: added slash to run_locally script_repository variable

Script Files/DAIL/DAIL - CITIZENSHIP VERIFIED.vbs
BLIP: Updating the Citizenship/ID DAIL scrubber to require that the user select the specific household members to update, instead of the household members to not update. The script will not allow you to continue until you have selected at least one household member, and that (those) member(s) should be listed on DAIL/DAIL.
=> Resolves #1967 Updating Citizenship DAIL Scrubber

Script Files/DAIL/DAIL - SEND NOMI.vbs
BLIP: Changed way script reads TIKL by just reading entire date and time in one line and making it one variable.
Figured that reading the entire rest of the sentence would make sense. I also accounted for an extra 3 digits for MM DD and HH
=> Resolves #1970 script reads entire date/time now

Script Files/BULK/BULK - REVW-MONT CLOSURES.vbs
BLIP: changed "Client needs to reapply for (PROGRAM) on (DATE)" to "Client needs to turn in new application for (PROGRAM) on (DATE)" to be more clear as to client responsibility and reapplication processing guidelines. Also more closely matches NOTES - CLOSED PROGS verbiage.
=> Resolves #1968 reworking verbiage about reapplying

Script Files/DAIL/DAIL - NEW HIRE.vbs
added functionality to account for the DAIL new hire update where it will sometimes say "UNKNOWN" as the hire date instead of an actual date. Not able to test this until there are new hire matches again.
=> Resolved #1984: added functionality to the new hire scrubber

Script Files/BULK/BULK - REVS SCRUBBER.vbs
changed logic to prevent issues where MS and ACTV renewals were being assessed as MF and ACTV thus not deleting them if there was a SNAP CSR or renewal in 12 more months.
=> Tackling MF = MS issue

Script Files/NOTES/NOTES - CAF.vbs
Blip - 'Enhanced script with error handling if CAF is more than 30 or 45 days old and TIKL for denial is checked.'
=> Resolved #1982 - NOTES - CAF TIKL Error Handling

Script Files/NOTICES/NOTICES - MFIP ORIENTATION.vbs
Blip: Corrects a bug that was preventing user-entered addresses from displaying on the memo sent to clients.
=> Resolves #2012 Bug with MFIP Orientation Notice addresses

Script Files/BULK/BULK - REPT-REVS LIST.vbs
BLIP: changed some internal variables to make sure script doesn't derail for agencies who's computers define the date constant without preceding zeroes 3/16/2016 vs 03/16/2016
=> Resolves #2014 fixed footer month issue

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Blip: Fixes a bug that was causing errors on cases with ended UNEA income.
=> Resolves #2018 Banked Month Fiater bug

Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
Blip: The script has been programmed to check for MAXIS timing out, but that appears to be forcing through a transmit which jumps ahead 1 JOBS panel. The script we now re-write the desired JOBS panel number to undo that jump. (Now for release as well)
=> Resolves #2065 Returning to selected JOBS panel

Script Files/NOTES/NOTES - SIGNIFICANT CHANGE.vbs
Changed denial reason "Income didn't decline at least 50% in the benefit month" to "Income did not decrease enough to qualify" since the policy on Significant Change is different from when the script was originally written.
=> Resolves #2035 Updated Denial reason

Script Files/NOTICES/NOTICES - BANKED MONTHS WCOMS.vbs, Script Files/NOTICES/NOTICES - MAIN MENU.vbs
BLIP: Adds WCOMS based on selection from 3 options
All banked months used = "You have been receiving SNAP banked months. Your SNAP is closing for using all available banked months. If you meet one of the exemptions listed above AND all other eligibility factors you may still be eligible for SNAP. Please contact your financial worker if you have questions."
Banked months notifier = "You have used all of your available ABAWD months. You may be eligible for SNAP banked months if you are cooperating with Employment services. Please contact your financial worker if you have questions."
Closing for E/T non-coop = "You have been receiving SNAP banked months. Your SNAP case is closing because CLIENT NAME did not meet requirements of working with Employment and Training. If you feel you have Good …
=> RESOLVES #2039 Adding NOTICES - BANKED MONTH WCOMS

Script Files/UTILITIES/UTILITIES - TRAINING CASE CREATOR.vbs
BLIP: Note added to warn users that on MSA/SNAP cases the MSA grant may not be budgeted for the initial month of SNAP.
=> RESOLVES #2044 Adding note about MSA into SNAP budget

Script Files/ACTIONS/ACTIONS - HOUSING GRANT MONY CHCK ISSUANCE.vbs
Added option in case notes that will allow non-exempt MFIP housing grant cases to have an accurate case note.
=> Resolved #2116, case notes for non-exempt cases

Script Files/DAIL/DAIL - SEND NOMI.vbs
BLIP: verbiage on question about when to send NOMI was reworked to read better to end users. Corrected issue that caused infinite loop when trying to run in inquiry.
=> RESOLVES #2098 correcting verbiage/adding state_a_blank_case_note

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs
BLIP: reworked verbiage on 30 day reinstate checkbox. Should be more clear for end user when to use this checkbox.
=> RESOLVES #2114 Reworking verbiage on 30 day reinstate

Script Files/NOTES/NOTES - LTC - 5181.vbs
BLIP: "Added case noting when the 'sent 5181 to case manager' check box is checked. Behind the scenes: updated the script end procedure message, and moved the stats block to the beginning of the script."
=> Resolved #2118, added case note for 'sent 5181 to case manager' check box

Script Files/ACTIONS/ACTIONS - MAIN MENU.vbs
BLIP: title was displaying incorrectly, corrected to ACTIONS Scripts.
=> RESOLVES #2125 fixing title of main menu dialog

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
Blip: Fixes a bug that caused the script to error and stop if the number of months approved for banked months was left blank.
=> Resolves #2133 Approved Progs Banked month dialog bug

Script Files/NOTES/NOTES - DENIED PROGRAMS.vbs
BLIP: This update prevents the script from duplicating the reason for "Coding for denial" when case noting.
=> Resolves #2141 -- Resolving duplicate case note bug

Script Files/NOTICES/NOTICES - MAIN MENU.vbs
BLIP: fix to link name, script couldn't find banked month WCOM script due to typo.
=> RESOLVES #2149 fixing link name

Script Files/SETTINGS - GLOBAL VARIABLES.vbs
BLIP: The `county_name` variable was removed from Global Variables, as the new function `get_county_code` determines this programmatically.
=> Resolved #2145: county_name removed from Global Variables

Script Files/BULK/BULK - DAIL REPORT.vbs
BLIP: The script was enhanced to allow users to select which type of DAIL message to add to the DAIL report. The default selection will remain "All" DAIL messages. Also on the back end: updated the functionality to allow users to enter their password if they have been 'passworded' out, and moved statistical information to the top of the script per new guidelines."
=> Resolves #2136, BULK DAIL REPORT user option added to select DAIL type

Script Files/DAIL/DAIL - NEW HIRE NDNH.vbs, Script Files/DAIL/DAIL - NEW HIRE.vbs
BLIP: When a client gets a new hire and someone else has used their SSN the names do not match. The script was not reviewing these inconsistencies. Now the script will pause if the names are not identical and give the user a chance to review the information and stop the script if necessary.
=> RESOLVES #2179 Adding safeguard for non matching new hire names

Script Files/BULK/BULK - CASE NOTE FROM LIST.vbs, Script Files/BULK/BULK - MEMO FROM LIST.vbs, Script Files/BULK/BULK - TIKL FROM LIST.vbs, Script Files/BULK/BULK - UPDATE EOMC LIST.vbs
Replaced with the following logic: `call file_selection_system_dialog(excel_file_path, ".xlsx")	'Selects an excel file, adds it to excel_file_path`
Blip: The script was updated to replace the Excel file browser with the Windows standard file browser, which contains logic for looking at recent places, favorite locations, and multiple shared drives.
Scripts updated:
* CASE NOTE FROM LIST
* MEMO FROM LIST
* TIKL FROM LIST
* UPDATE EOMC LIST
=> Resolves #2008: BrowseForFile is now history

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Blip: Resolves a bug that caused the script to stop on UNEA panels with $0 coded on the SNAP PIC.
=> Resolves #2177 Banked Month Fiater $0 Unea bug

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
Blip: The script now wraps up on SPEC/WCOM, as the user is instructed to
check SPEC/WCOM for notice clarity.
=> Resolved #2134: Approved Programs now ends on SPEC/WCOM

Script Files/NOTES/NOTES - MFIP TO SNAP TRANSITION.vbs
Blip: Corrects a minor bug that may have caused the script to read the incorrect footer month in MAXIS.
=> Resolves #2228 NOTES - MFIP TO SNAP footer_year bug

Script Files/NOTES/NOTES - CLIENT TRANSPORTATION COSTS.vbs
Blip: a variable was fixed which was defined incorrectly.
County-specific logic for Wabasha County should now be working
correctly.
@ramonalisa1, if this wasn't working correctly, it should soon be!
=> Resolved #2231: clientworker_county_code is now worker_county_code

Script Files/NOTES/NOTES - BURIAL ASSETS.vbs
BLIP: Script will no longer require input when NONE is selected as burial agreement type, it also allows users to write their own burial agreement type.
=> RESOLVES #2239 fixing dialog_01 burial assets

Script Files/ACTIONS/ACTIONS - MA-EPD EI FIAT.vbs, Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs
BLIP: Script can now handle change in position of HC income estimator. Script can do this as well as current location of estimator to make the transition to the new panel more smooth if both version are available at the same time.
=> RESOLVES #2251 Accounting for change to JOBS panel

Script Files/BULK/BULK - REPT-REVS LIST.vbs
REPT REVS List has_content_check has been updated to look for an entire case number rather than one digit, eliminating missed cases on the bulk list.
=> Resolved #2258 (partial): Fixed content check/REVS

Script Files/BULK/BULK - REPT-REVW LIST.vbs
REPT REVW List has_content_check has been updated to look for an entire case number rather than one digit, eliminating missed cases on the bulk list.
=> Resolved #2258 (partial): Fixed content check/REVW

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs, Script Files/DAIL/DAIL - ABAWD FSET EXEMPTION CHECK.vbs
BLIP: Reworking verbiage to better follow 0028.06.12. It will now read: "appears to be working 30 hours/wk (regardless of wage level) or earning equivalent of 30 hours/wk at federal minimum wage. Please review for ABAWD and SNAP E&T exemptions." rather than not mentioning working 30 hours a week
=> RESOLVES #2270 Reworking verbiage on working 30 hours/equivalent 

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs
Updated to notify worker if Spec/Memo is unable to be accessed. Added verbiage to include this could be because the worker does not have authorization to send a Spec/Memo. Script originally only had a message that the worker could be in Inquiry mode.
=> Resolves #2269

Script Files/NOTES/NOTES - CLOSED PROGRAMS.vbs
BLIP: Script will now correctly handle expedited snap closures for no postponed verification returned. Per CM 4.12; 5.09.06; 5.12.15.09; 05.12.15.03; 05.12.15.15 client's who apply on or before the 15th of a month have 30 days from application date to turn in verification. After that they must reapply. Clients who apply after the 15th have until the date of closure to turn in verification. After that they must reapply. Also changed HCPM button to direct to new HC Eligibility program manual.
=> RESOLVES #2333 AND #2334 adding rein dates for expedited SNAP and changing links

Script Files/BULK/BULK - INAC SCRUBBER.vbs
BLIP: The INAC Scrubber can now be used to bypass MMIS should the user not have access. As a safeguard, it will not transfer cases that closed in the INAC month on health care to Closed Cases. Additionally, err_msg handling has been added for simpler data validation, and the dialog has been renamed Dialog1 for chainloading.
=> Resolves #2292 and Resolves #2336 -- Updates to INAC Scrubber

Script Files/BULK/BULK - CHECK SNAP FOR GA RCA.vbs
BLIP: Fixing a bug that was causing holes in the output of the report.
=> Resolves #2364 -- Swapping an AND for an OR in CHECK SNAP FOR GA RCA

Script Files/BULK/BULK - DAIL REPORT.vbs
Blip - 'Fixes an error in the script when a caseload has a privileged case in it.'
=> Resolves #2403 - DAIL Report Bug with Priv Cases

Script Files/BULK/BULK - INAC SCRUBBER.vbs
BLIP: when running the script in developer mode the script will now pause and display the case number, and the CLS number it is being transferred to.
=> RESOLVES #2392 Adding pause for dev mode

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs
Added the option to choose Dual Sanctions (CS & ES) type. Also changed sanction reason dropdown box to a combo box so the worker is able to type in a reason since dual sanctions will need to indicate two reasons.
=> Resolves #2413 Added option for Dual sanctions

Script Files/UTILITIES/UTILITIES - TRAINING CASE CREATOR.vbs
Blip - 'The year of birth for a client in a scenario will be calculated by having the scenario indicate the clients age at application.'
=> Resolves #2396 - Training Case Creator Age Bug

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
BLIP (for issue 2415): Removed the navigation to SPEC/WCOM after the case note has been made. The script will revert to ending in CASE/NOTE in edit mode. Also updated the script closing text to reflect that the script is not in SPEC/WCOM.
BLIP (for issue 2373): For Hennepin and Ramsey County users, removed Excel list created when the case is identified as banked months. Hennepin and Ramsey County use the process detailed in the BULK - BANKED MONTHS REPORT (https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/Script%20Instructions%20Wiki/Banked%20Months%20Report.aspx) 
For all other users that do use gather statistics using a database (St. Louis County) a message box will pop up informing users that the Excel spreadsheet functionality will be retired as of the August 2016 script release …
=> Resolved #2415, Resolved #2373: NOTES - Approved Programs 

Script Files/BULK/BULK - REVS SCRUBBER.vbs
BLIP: The WB program field has been removed from the REPT/REVS screen. Update cash status field to account for this update.
=> Resolved #2430, Updated where CASH status field is read

Script Files/NOTICES/NOTICES - METHOD B WCOM.vbs
BLIP: Script will no longer write the health insurance premium twice on the WCOM, it will also only autofill the medicare premium if it is coded as Y for apply to spenddown/budget on MEDI.
=> RESOLVES #2433 Bug fix, medicare must be Y, remove duplicate writing

Script Files/NOTES/NOTES - LTC - TRANSFER PENALTY.vbs
BLIP: Name of script had incorrect category name. Changed category name from NOTE to NOTES.
=> Resolved #2441, Updated name of script variable for LTC Transfer Penalty 

Script Files/BULK/BULK - REPT-PND2 LIST.vbs
BLIP: For MULTICOUNTY users this script was using the wrong variable to determine the list of users to run on.
=> RESOLVES #2458 changing variable for PND2 script

Script Files/ACTIONS/ACTIONS - ABAWD FSET EXEMPTION CHECK.vbs, Script Files/BULK/BULK - BANKED MONTHS REPORT.vbs, Script Files/DAIL/DAIL - ABAWD FSET EXEMPTION CHECK.vbs
BLIP: Fixed a bug for cases in which HH member has more than one job. The 1st job was being skipped. All jobs now being read, and included in income calculation. 
Also fixed a bug to correctly multiply prospective hours for all jobs. 
This bug was fixed in all three scripts included in the pull request.
=> Resolved #2456: Exemption check bugs

Script Files/ACTIONS/ACTIONS - TRANSFER CASE.vbs
BLIP: Script will not correctly find the new worker's name (it was only reading for Aliases before) and include the new workers complete information in the body of the MEMO.
=> RESOLVES #2438 Adding handling for non-alias workers

Script Files/NOTES/NOTES - APPROVED PROGRAMS.vbs
BLIP: Interest was presented in keeping the excel functionality available for the banked months tracking. As such it won't be retired and the warning message box has been removed.
=> RESOLVES #2373 Removing warning box

COMPLETE LIST OF SCRIPTS.vbs, Script Files/ACTIONS/ACTIONS - FSET SANCTION.vbs
BLIP: Option added within the 'resolved sanction' option: If the recipient resolves their sanction prior to the sanction effective/imposed date, the case note reflects that the sanction was deleted, and the 'number of sanctions' field is cleared on STAT/WREG. The script has also moved from the MAIN ACTIONS menu to the ABAWD ACTIONS menu, and several functions and mandatory field criteria was updated on the back end.
=> Resolved #2480, Fset sanction updates

Script Files/ACTIONS/ACTIONS - ACCT PANEL UPDATER.vbs
BLIP: Script will now warn users if unable to edit, it can update if there are more than 9 account panels. Also implemented some behind the scenes revamping including:
- deleted extraneous dialog
- script will now convert what it finds on ACCT panel for all variables on the dialog
- new handling no longer requiring to enter count codes for programs that aren't active/pending
=> RESOLVES #2465 handles no edit mode, 10+ accounts, and other fixes

Script Files/BULK/BULK - BANKED MONTHS REPORT.vbs
BLIP: Several enhancements to the script have been made. ABAWD month counting and filtering of banked months has been streamlined. All other updates are to add rejected cases to the rejected banked months list, along with the reason for rejection. Cases are now rejected for the following reasons:
Cases that can't access person notes
Cases that are coded 30/11
Cases that aren't coded as a 30/10
Cases that are prorated, but the approval is not prorated
Cases where the script cannot access the ABAWD tracking record
Cases where the report date is not coded as a counted ABAWD month on the ABAWD tracking record
=> Resolved #2479, Banked months report enhancements

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs, Script Files/ACTIONS/ACTIONS - LTC - SPOUSAL ALLOCATION FIATER.vbs, Script Files/ACTIONS/ACTIONS - NEW JOB REPORTED.vbs, Script Files/ACTIONS/ACTIONS - PAYSTUBS RECEIVED.vbs, Script Files/DAIL/DAIL - NEW HIRE NDNH.vbs, Script Files/DAIL/DAIL - NEW HIRE.vbs
BLIP: Scripts were updated to prepare for the change to the jobs panel including moving fields. This is only for the critical issue of the scripts pointing at the wrong place. New types for SCHL/JOBS/UNEA to be added once we get hands on the panels.
=> RESOLVES #2485 Fixed scripts which point to changing fields (RELEASE)

Script Files/NAV/NAV - DAIL-WRIT.vbs
BLIP: Script has been reworked so it no longer transmits off of the current panel/list allowing user to keep the case numbers they want to see in front of them to enter in the script if needed.
=> RESOLVES #2475 leaving current panel issue

Script Files/NOTES/NOTES - CAF.vbs, Script Files/NOTES/NOTES - HRF.vbs
CAF BLIP: Added EMPS panel field to the CAF 1 dialog. This field will be auto-filled with the information for all HH members on the case. Also added EMPS, SANC and TIME navigation buttons, removed the WB ELIG navigation and updated the password check handling on the back end. 
For Hennepin County and Ramsey County workers: a checkbox has been added "Sent MFIP financial orientation DVD to participant(s)." This check box will case note if a participant has been given a financial orientation DVD."
HRF BLIP: Added EMPS panel field to the main dialog. This field will be auto-filled with the information for all HH members on the case. Also added EMPS, SANC and TIME navigation buttons, update dates to global constants and updated the password check handling on the back end.
=> Resolved #2487, Resolved #2498: EMPS panel and family cash navigation 

Script Files/NOTES/NOTES - CAF.vbs
BLIP: Notes on income is now a mandatory field if the case has income on it. This change is to encourage users to write explanations of income in the CAF case notes to better meet adequate case note requirements.
=> RESOLVES #2482 Making Notes on income mandatory

Script Files/NOTICES/NOTICES - NOMI.vbs
BLIP: For Hennepin County users only - Fixed bug that would not allow the automatic TIKL on case where the application date is 60 days older than the NOMI date when sending the second NOMI. Also added handling to the automatic TIKL to unsure that cases that are being issued a NOMI between pending days 51-60 are allowed 10-day notice.
=> Resolved #2543, NOMI bug for x127 users

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs, Script Files/NOTICES/NOTICES - SNAP E AND T LETTER.vbs
BLIP: Added safeguard to disallow counties who are exempt from ABAWD work requirements to use this script.
(changing to a problem as in 7 days it becomes one)
=> RESOLVES #2497 Adding newly exempt counties

Script Files/NOTES/NOTES - EXPEDITED DETERMINATION.vbs
BLIP: Fixed issue where the ABAWD explanation information does not carry over to case note. Also the reason for the expedited delay will case note whether or not the application is greater than 7 days or not.
=> Resolved # 2553, Exp determination bug fix

COMPLETE LIST OF SCRIPTS.vbs, Script Files/DAIL/DAIL - DAIL SCRUBBER.vbs, Script Files/DAIL/DAIL - WAGE MATCH SCRUBBER.vbs
BLIP: This new script helps workers process WAGE DAILs. The script grabs quarterly earnings information from the match as well as earned income information for the case and presents that information in an organized dialog to the financial worker. The script does not update or case note anything, but it does save the financial worker time and improves the accuracy of transcribing earned income information from the matches.
=> Resolves #2583 -- Adding Wage Match Scrubber to DAIL Scrubber

Script Files/ACTIONS/ACTIONS - ABAWD BANKED MONTHS FIATER.vbs
Blip - 'Bug fixes to the script. The script will stop early in the run if the REVW date has not been entered and alert the worker to the reason for the error. The script also has a way to account for resources and handle adjusting the expedited status based on the information provided.'
=> Resolves #2491 & Resolves #2623 - Banked Months FIATER

Script Files/BULK/BULK - REVS SCRUBBER.vbs
Blip - 'Fixes a bug that causes an error at the end of the script run if no PRIV cases are found.'
=> Resolves #2662  - REVS Scrubber

Script Files/NOTES/NOTES - GRH - NON-HRF-POSTPAY.vbs
BLIP: Invalid character was left in code. deleted it, script should work now.
=> Removing invalid character

Script Files/NOTES/NOTES - MFIP SANCTION AND DWP DISQUALIFICATION.vbs
BLIP: Updated non-CS sanction and non-consecutive month sanction's resolved date to be 10 days prior to the end of the month.
=> Resolved #2700, MFIP sanction 10 day bug in release

notes/caf.vbs, notes/csr.vbs, notes/explanation-of-income-budgeted.vbs
Blip - 'In order to provide better detail about income and how it is budgeted, there is now a button on the 'Notes on Income' area of the CAF, CSR, and Explanation of Income Budgeted' script that will allow workers to select from some predetermined options.'
=> Resolves #2578 - Options for Notes on Income

notes/hc-renewal.vbs
Added space after Verification's received if Agencies have Global Variables set to have Verification needed at the top of the case note instead of the bottom of the case note.
=> Added space after verifs recd

notes/hcapp.vbs
Allows agencies the option to have the verification's needed at the top of case notes and places a space after that line to separate Verification needed from the rest of case notes.
=> Added space after Verifs needed if at the top

Script Files/DAIL/DAIL - CSES SCRUBBER.vbs
Fixes a bug that caused the script to error when seeking information from cases with an ineligible SNAP version approved.
=> Resolves #2738 CSES processing Bug

bulk/check-snap-for-ga-rca.vbs
BLIP: This update to the script corrects a typo that was preventing the script from running.
=> RE: #2710 Correcting error in Check SNAP for GA RCA

dail/cses-scrubber.vbs
Script should look at the correct MF ELIG month.
Script will end for SNAP or MFIP pending as these should be manual processes for initial set up. Script currently errors in pending cases - now it will stop early in the run.
=> #2824 & #2830 - Some minor CSES Scrubber repair work

notes/mfip-sanction-and-dwp-disqualification.vbs
Update to have the case note erad a 'SPEC'LETR' was sent for future closed sanction month.
This is to replace Pull #2882 as that change was made on the wrong file.
=> #2880 Changing note wording to SPEC/LETR

notes/emergency.vbs, notes/interview-completed.vbs, notes/ltc-cola-summary.vbs, notes/ltc-intake-approval.vbs, notices/ltc-asset-transfer.vbs
#2915 NOTES INTERVIEW COMPLETED: updated to allow to use in CM + 2
#2954 NOTICES - LTC Asset transfer: updated SPEC/MEMO function
#2897 NOTES - EMERGENCY: resetting crisis variable to prevent duplicate header
#2934 NOTES - LTC COLA SUMMARY: updated case note header to read MAXIS footer month
#2948 NOTES - LTC INTAKE APPROVAL: moved cancel confirmation
=> #2915, #2954, #2897, #2934, #2948 NOTICES/NOTES issue
